- .travis.yml
- README.md
- dmscripts/env.py
- dmscripts/logging.py
- scripts/index-services.py
Updated version of the index_services.py scripts from
digitalmarketplace-api repository. New version:
* supports retries for all list services and indexing requests
* takes environment name instead of the two API endpoints
* can use any index name instead of the `g-cloud` default
* uses `dmutils` logging format
Takes a stage name and returns the full API endpoint for Data or
Search APIs.
Used to configure 'dmutils' and 'script' logger with dmutils logging
handler. Logging levels can be modified for any additional loggers.
> Add index-services script

- scripts/index-services.py
index-services is used for nightly index updates, during which it
uses the main alias as the request index. Trying to create an index
fails in this case since an alias with the same name already exists.
Index creation is skipped when --index is set to an alias name. Any
other error response during index creation will abort the script.
> Skip index creation when alias exists with the same name

- dmscripts/insert_framework_results.py
- requirements.txt
- scripts/insert-framework-results.py
- tests/fixtures/framework_results.csv
- tests/test_insert_framework_results.py
For use when the pass/fail results for suppliers come in from CCS.
The script here may be subject to change as we don't yet know the format of data we'll get from CCS - this assumes a basic CSV with just `supplier_id` and `pass/fail` per row.  If we also get supplier name it would be good to modify the script to check the supplier name matches the ID before updating, as a sanity check.
> Script to update API with pass/fail for suppliers

- dmscripts/generate_framework_agreement_data.py
- requirements.txt
- tests/test_generate_framework_agreement_data.py
This is the version of the script that I used to generate the final files for CCS that they are happy with.
Compared to the previous version it:
* fixes the numbering of lots (PaaS and SaaS were the wrong way round)
* also generates a file for failed suppliers
* changes the key to have supplier name first
This now uses the new sanitise supplier name method and so depends on this being merged first:
> Fix lots in export

- dmscripts/generate_questions_csv.py
- scripts/generate-questions-csv.py
- tests/test_generate_questions_csv.py
Port over the script that generates a CSV file with all the declaration questions followed by all of the service questions (lots are separated by a blank line).  If [question hints](https://github.com/alphagov/digitalmarketplace-frameworks/blob/master/frameworks/digital-outcomes-and-specialists/questions/declaration/canProvideFromDayOne.yml#L4) or [multiquestion hints](https://github.com/alphagov/digitalmarketplace-frameworks/blob/master/frameworks/digital-outcomes-and-specialists/questions/services/agileCoach.yml#L16) are present, they'll be included.
[Checkbox descriptions](https://github.com/alphagov/digitalmarketplace-frameworks/blob/master/frameworks/digital-outcomes-and-specialists/questions/services/userExperienceAndDesignTypes.yml#L9), if they exist, are appended to labels.
Output …
> Generate a CSV file with all the declaration/service questions

- dmscripts/generate_framework_agreement_data.py
- dmscripts/generate_user_email_list_applications.py
- dmscripts/generate_user_email_list_declarations.py
- dmscripts/insert_framework_results.py
- dmscripts/logging.py
- requirements.txt
- scripts/bad_words.py
- scripts/check-g-cloud-live.py
- scripts/generate-framework-agreement-data.py
- scripts/generate-user-email-list-applications.py
- scripts/generate-user-email-list-declarations.py
- scripts/index-services.py
- scripts/insert-framework-results.py
- scripts/make-g-cloud-7-live.py
- scripts/oneoff/fix-agreement-extensions.py
- scripts/oneoff/rename-west-england.py
- scripts/set-search-alias.py
- tests/test_generate_framework_agreement_data.py
- tests/test_generate_user_email_list_applications.py
- tests/test_generate_user_email_list_declarations.py
- tests/test_insert_framework_results.py
Adds digitalmarketplace-apiclient to the list of requirements and
changes all `dmutils.apiclient` imports to `dmapiclient`.
Since apiclient is using a logger with the package name this also
requires changing the configured loggers in dmscripts/logging and
individual scripts to include `dmapiclient`.
API client `1.0.1` retries 504 responses.
Multiprocessing `Pool.imap` doesn't raise an exception if the iterator
fails to produce any results 👽👽👽 (ie when the first API request fails),
making the process exit with a 0 status. This will mark the CI job
as successful when the indexing failed to run.
Replacing `Pool` with `ThreadPool` seems to fix the problem, and other
scripts are already using `ThreadPool`. Also replacing `.imap` with
`.imap_unordered` since we don't really care about the …
> Use dmapiclient

- requirements.txt
- scripts/bulk-upload-countersigned-agreements.py
This should be a one-time- (or few-times-at-most)-use script to upload the first batch of countersigned G7 framework agreements when we get them from CCS.
See: https://www.pivotaltracker.com/story/show/109718484
Depends on:
> Bulk upload countersigned agreements

- dmscripts/insert_dos_framework_results.py
There was a bug in the script where it dies if the declaration had not been started so came back as `None`; this fixes it.
> Bugfix to handle case where declaration has not been started

- dmscripts/export_dos_suppliers.py
- scripts/export-dos-suppliers.py
- tests/conftest.py
- tests/test_export_dos_suppliers.py
- tests/test_insert_dos_framework_results.py
Export DOS application information into three CSV files for successful,
failed and discretionary applications.
This script assumes that `insert-dos-framework-results.py` has already
been run and will fail with an assertion error if it has not (when it
comes across a declaration that is not complete while the supplier is
not marked as failed.
The file of successful applicants contains supplier information, contact
details and counts for completed, failed and draft services.
The file of failed applicants contains supplier information, a list of
failed mandatory questions, contact details and counts for completed,
failed and draft services.
The file of discretionary applicants contains supplier information,
discretionary questions and their answers, contact details and counts
for completed, …
> Export DOS applications

- dmscripts/insert_dos_framework_results.py
- requirements.txt
- tests/test_insert_dos_framework_results.py
The API Client method `update_draft_service` can't be used to update the status of a service.
The new `update_draft_service_status` method should be used instead.
> Bugfix: Really update draft service status

- scripts/oneoff/set-agreements-content-disposition.py
Finds agreement files that have the supplier name in the path and
renames them, so that links don't break if suppliers change their
name in the database.
Old file name is set as Content-Disposition header filename, so that
when file is downloaded it's saved with has supplier name in the
file name.
> Add a script to remove supplier name from agreement file paths

- requirements.txt
- scripts/clear-signed-agreements.py
Removes signed agreement files and unsets `agreementReturned` flags
for given framework.
Used when original framework agreement document has been changed and
all suppliers are required to sign the new agreement PDF.
> Add clear-signed-agreements script

- dmscripts/generate_questions_csv.py
- scripts/generate-questions-csv.py
The unicode changes here might not actually be required (I think it was LibreOffice choking rather than a problem with the output that prompted me to make them), but brings the script into line with how we do things in most other scripts with unicode/CSVs.
> Minor tweaks to question csv script

- scripts/clear-signed-agreements.py
The existing `clear-signed-agreements.py` script
will delete all the agreements for each supplier
in the given framework.
This adds the ability to specify certain suppliers
in that framework to target.
Related to the story to upload 2 new framework agreements: https://www.pivotaltracker.com/story/show/119371899
> Allow agreements to be cleared individually

- dmscripts/export_g8_suppliers.py
- dmscripts/insert_g8_framework_results.py
- scripts/export-g8-suppliers.py
- scripts/oneoff/insert-g8-framework-results.py
- tests/test_export_g8_suppliers.py
- tests/test_insert_g8_framework_results.py
Completes this story: https://www.pivotaltracker.com/story/show/121427817
And also: https://www.pivotaltracker.com/story/show/121427955
For each G-Cloud 8 application the first script:
* gets the supplier declaration
* checks whether it is a PASS, FAIL or DISCRETIONARY
* updates the `supplier_frameworks` entry for the application accordingly, using the API:
- on_framework=true if declaration OK and at least one completed service
- on_framework=false if declaration FAILed or there are no completed services
- on_framework=NULL (no call to API) if declaration DISCRETIONARY and at least one completed service
And then the second script generates three CSV files with relevant data for each of passed/failed/discretionary applications.  Suppliers who expressed interest but didn't complete an …
> [#121427817] Add scripts to set G8 results and export pass/fail/discretionary for CCS

- dmscripts/export_dos_suppliers.py
- dmscripts/framework_utils.py
- dmscripts/insert_dos_framework_results.py
- dmscripts/insert_g8_framework_results.py
- scripts/check-g-cloud-live.py
- scripts/make-dos-live.py
- scripts/make-g-cloud-live.py
- scripts/update-framework-results.py
- tests/test_framework_utils.py
- tests/test_insert_dos_framework_results.py
- tests/test_insert_g8_framework_results.py
~~The previous version of this script only updated results for DOS.  This can now be used for any framework.~~
Useful for completing these chores: 
https://www.pivotaltracker.com/story/show/126020263
https://www.pivotaltracker.com/story/show/126119097
This has grown a bit since initial PR- I've extracted some common methods into a  `framework_utils` file and adjusted existing scripts accordingly, and also tweaked the `make-g-cloud-live` script to work for the new document paths for G-Cloud 8 (this is legit because it should be the same for new frameworks going forward).
> Generalise script for all frameworks, not just DOS

- scripts/clear-signed-agreements.py
This is the version we've run to remove G8 signed agreements after
fixing lot numbering. It adds <cutoff_time> support to only remove
agreements uploaded before given time.
> Update clear-signed-agreements script

- dmscripts/email.py
- dmscripts/generate_agreement_signature_pages.py
- dmscripts/html.py
- dmscripts/notify_buyers_when_requirements_close.py
- email_templates/requirements_closed.html
- requirements.txt
- requirements_for_test.txt
- scripts/export-dos-outcomes.py
- scripts/export-dos-participants.py
- scripts/export-dos-specialists.py
- scripts/export-dos-suppliers.py
- scripts/export-g8-suppliers.py
- scripts/generate-questions-csv.py
- scripts/notify-buyers-when-requirements-close.py
- tests/helpers.py
- tests/test_export_dos_suppliers.py
- tests/test_export_g8_suppliers.py
- tests/test_generate_questions_csv.py
- tests/test_notify_buyers_when_requirements_close.py
Rendering html is required for emails, so moving the function from a script-specific dmscripts module.
Includes briefs `with_users` request and `send_email` custom logger. Content loader has been split up since the last time utils were updated, so this adds dmcontent as a new dependency and updates all import paths.
Using 1.0.0 version of content-loader since the latest one breaks tests.
Requests tagged messages from Mandrill history. Mandrill stores sent messages for 7 days and filtered by tag we don't expect to send more than 1000 messages so we can avoid adding pagination for now.
Note that messages don't appear in Mandrill search API response until they've been delivered, so rerunning the send script right away will probably end up sending duplicate emails.
Gets the list of briefs …
> Notify buyers when briefs close

- requirements.txt
- scripts/oneoff/save-signed-agreement-path.py
For suppliers who have returned their framework agreement, if there is no signedAgreementPath set in the FrameworkAgreement table then check s3 for their most recently uploaded signed framework agreement file and update the FrameworkAgreement record with this file path.
> Add script to save signedAgreementPath

- requirements.txt
- scripts/oneoff/save-countersigned-agreement-path.py
Save `countersignedAgreementPath` and `countersignedAgreementReturnedAt` for framework agreements. For suppliers who have returned their framework agreement and had it countersigned (indicated by a countersigned file in s3), we set their `countersignedAgreementPath` and
`countersignedAgreementReturnedAt` in the FrameworkAgreement table. The time for the `countersignedAgreementReturnedAt` is taken from s3 meta data for when the file was uploaded (this is likely the closest indicator we have for when a file was countersigned).
> Save countersigned details for framework agreements

- dmscripts/models/modeltrawler.py
- dmscripts/models/process_rules.py
- dmscripts/models/utils.py
- dmscripts/models/writecsv.py
- requirements.txt
- scripts/get-model-data.py
- tests/models/test_modeltrawler.py
- tests/models/test_process_rules.py
- tests/models/test_utils.py
Created a class that gets back all table rows from the database using the API and prints them to CSV.  In theory, works for anything with an "iter" method, and in practice works out of the box for `buyers`, `suppliers`, `briefs`, and `brief_responses`.
Ash is asking for weekly printouts of (DOS-related) data, and so this is the first step.  
👉  [This is the data he's looking for](https://docs.google.com/spreadsheets/d/1DlkUYNSDgK1vjNB4LQgKP6AQJD9g89kOAw5MPwTVPqs/edit?ts=57e513ba#gid=0). 👈 
Things left to do in subsequent stories are:
- [Join logic](https://www.pivotaltracker.com/story/show/132760553): (ie, how many applications do we get per published brief)
- [Set up a regular jenkins thing](https://www.pivotaltracker.com/story/show/131737693) that prints out stuff once a week
> Get back model data and output to CSV

- dmscripts/export_framework_applicant_details.py
- dmscripts/generate_agreement_signature_pages.py
- scripts/generate-agreement-signature-pages.py
- scripts/generate-counterpart-signature-pages.py
- tests/test_export_framework_applicant_details.py
For this story: https://www.pivotaltracker.com/story/show/128842655
I started off trying to parameterise the `generate-agreement-sinature-pages` script, but it turns out that there are enough differences with generating the counterpart pages that it makes more sense to me as a separate (but very similar) thing.
The main differences are different conditions on when a file should be generated, an extra file that needs to be copied and later removed, (i.e. the signature file), and file names.
It could probably have been parameterised and just one script, but that would have involved an explosion of command line arguments and/or a bunch of conditional steps in generate_agreement_signatre_pages.py` that wouldn't be very pretty.
> Script to generate counterpart G-Cloud 8 PDFs

- setup.cfg
####This should pass once the intermittent test failure fix is merged  https://github.com/alphagov/digitalmarketplace-scripts/pull/73
As per https://github.com/alphagov/digitalmarketplace-api/blob/master/setup.cfg#L2
* Add venv3* to pytest `norecursedirs`
> NO-TICKET_add_venv3

- scripts/mark-definite-framework-results.py
docopt was interpreting a description line (mid-paragraph) beginning
with `--reassess-failed-draft-services` as a declaration of that option, and
so, it being declared twice, it was refusing to allow it to be used, claiming
`--reassess-failed-draft-services is not a unique prefix:...`
> mark-definite-framework-results: reformat description in docstring for docopt's sake

- dmscripts/export_framework_applicant_details.py
- tests/test_export_framework_applicant_details.py
- tests/test_mark_definite_framework_results.py
This fixes the logic related to story https://www.pivotaltracker.com/story/show/134342643 in two main ways:
- Includes `failed` services in the service counts
- Switches the `on_framework` column to the more general `pass_fail` which can take on the values `pass`, `fail`, `discretionary`, `pass_with_failed_services`, `discretionary_with_failed_services`.
Other than that it's a tidyup reducing unnecessary dict copying and adding a note that this script is under-tested. I feel I should move on to other items in the backlog rather than spending days writing tests for this (case in point note the fairly major behaviour changes in this PR that only required one tiny test change).
> [#134342643]export_framework_applicant_details dos2 followup

- scripts/get-model-data.py
Ash was getting confused that all successful brief_responses
were included in the `successful_brief_responses` CSV, including
responses for briefs that were later withdrawn (or drafts :/).
Thus he wants one extra column in the `successful_brief_responses`
CSV: the current status of the brief that was applied to.
He would like it to be the final column in the CSV.
> Add brief status to successful brief response CSV

- README.md
- dmscripts/send_stats_to_performance_platform.py
- scripts/send-stats-to-performance-platform.py
- tests/test_send_stats_to_performance_platform.py
This new script hits our API statistics endpoint and reformats the data into the form required by our performance platform datasets before posting it to the relevant place.
The stats reformatting methods (`_format_statistics`, `_label_and_count`, `_sum_counts`, `_find`) are based on those used in the admin app, but there are enough differences here that I don't think it's worth extracting these methods into shared utils right now.
I guess in future if the performance platform works out for us then the admin app stats views will become obsolete and be removed anyway.
> Add script to send stats to Performance Platform

- dmscripts/generate_framework_agreement_signature_pages.py
- scripts/bulk-upload-ccs-documents.py
- scripts/bulk-upload-documents.py
- scripts/generate-framework-agreement-counterpart-signature-pages.py
- scripts/generate-framework-agreement-signature-pages.py
- scripts/make-g-cloud-live.py
- scripts/upload-counterpart-agreements.py
Previously we needed to pass in a JSON file but now this JSON will come from the frameworkAgreementDetails an the API response for the framework.
> Update agreement-generation scripts to use details from API

- dmscripts/upload_counterpart_agreements.py
- scripts/upload-counterpart-agreements.py
- tests/test_upload_counterpart_agreements.py
Story https://www.pivotaltracker.com/story/show/127983495
One thing I'm considering is whether it's the right thing to swallow `EmailError` and continue to the next supplier - if we're not able to send an email we maybe don't want to blaze ahead and upload a bunch of files if there's a likelihood that *all* the emails are going to fail and we've just lost the chance to send the users emails...?
> [#127983495]upload_counterpart_agreement notifications

- dmscripts/helpers/service_faker_helpers.py
- dmscripts/json_schema_service_faker.py
- requirements.txt
- schemas/g-cloud-9.declaration.json
- scripts/mark-definite-framework-results.py
- scripts/oneoff/generate-fake-g-cloud-services.py
A new script which can be used to generate fake (G9) services from JSON Validation schemas.
* Add a minimalist JsonSchemaDataFaker class and JsonSchemaG9ServiceFaker subclass which accept a given JSON Validation Schema and reverse-engineers compatible data. These classes are implemented to the bare-minimum level required for generating services from G9 schemas, and are not guaranteed to generate data from any given generic JSON Validation Schema.
* Add the JSON Validation Schemas for cloud-hosting, cloud-software, cloud-support.
* Add a JSON Validation Schema for G9 supplier declarations.
* Add a '--ignore-documents' parameter to the `scripts/make-fake-g-cloud-services-live.py`, to bypass S3/document operations.
* Fix logging import in `scripts/mark-definite-framework-results.py`
*  Adds …
> Script to generate fake (G9) services to enable testing and iteration of search and summaries.

- scripts/get-model-data.py
For each brief, we know how many people applied to it, as well as how many people applied successfully/unsuccessfully.
Ash also wants to know how many people _could have_ applied to each brief, so we're putting some more stuff in the information about the applied-to briefs so that he can use a lookup table.
> Add `frameworkSlug` and `specialistRole` to final csv

- dmscripts/mark_definite_framework_results.py
- schemas/digital-outcomes-and-services-2.declaration.json
- tests/test_mark_definite_framework_results.py
Story https://www.pivotaltracker.com/story/show/141943157
It was going to be ugly to get the frameworks to automagically generate
an assessment schema that also included the `status` criteria, and what's
more we already do "special case" handling of the service "status" field.
also change included dos2 schema, no longer including `status`, to match
this.
> [#141943157]mark_definite_framework_results: make declaration "status" handling "special case"

- dmscripts/generate_framework_agreement_signature_pages.py
- dmscripts/upload_counterpart_agreements.py
- scripts/generate-framework-agreement-counterpart-signature-pages.py
- scripts/upload-counterpart-agreements.py
For this story: https://www.pivotaltracker.com/story/show/128842967
We need the Jenkins job to know if the PDF generation step hasn't worked as expected, so the script needs to return an error code.
Its also useful in dry-run mode to see what on earth the script would have done, so I'm unobfuscating email addresses in dry-run output.
> Return error if errors generating PDFs and unobfuscate dry-run emails

- dmscripts/helpers/framework_helpers.py
Running with 30 threads places undue stress on the API and increases page load times up to 40 seconds.
Let's try three threads and see if performance is impacted.
> Reduce the number of threads used by framework_helpers

- README.md
It's 4 different scripts, not only one script.
> Fixed copy-paste typos in the description of export-dos-*.py scripts

- dmscripts/helpers/supplier_data_helpers.py
- scripts/notify-successful-suppliers-for-framework.py
- scripts/notify-suppliers-whether-application-made-for-framework.py
Script for this story: https://www.pivotaltracker.com/story/show/141695173
It reuses the pattern from the existing `notify-successful-suppliers` script.  This one needs a slightly less complicated set of personalisation data so the new `AppliedToFrameworkSupplierContextForNotify` is pretty simple.  I discussed with Paul whether it should instead use the `modeltrawler` pattern but we decided that wasn't a good way to go right now (time constraints as much as anything else, but this also isn't quite the typical use-case for modeltrawler).
I hard-coded the Notify template IDs in the script as (1) these shouldn't change from framework to framework and (2) it feels less error-prone than people having to pass multiple template IDs as command line params.
The fetch of user data here is relying …
> Notify suppliers when framework closes

- scripts/send_dos_opportunities_email.py
Before it was only aborting if the last lot failed which was incorrect. The script should fail as soon as it comes across an error otherwise failures to previous lots will go undetected.
> Abort script if an individual lot fails to send

- dmscripts/generate_framework_agreement_signature_pages.py
Previously the generated PDFs had an ugly looking date format.  This makes it nicer.
The `'%d %B %Y'` format gives e.g. "29 March 2017"
Handy strptime reference here: https://docs.python.org/2/library/datetime.html#datetime.datetime.strptime
** EDIT **
Now also passes in `include_countersignature` param to template kwargs, so the template knows whether or not to include the countersignature.
~~(Corresponding update to agreements repo coming v. soon)~~
Corresponding update to agreements repo here:
> Dates should be formatted nicely in countersigned agreements

- dmscripts/helpers/env_helpers.py
Allows using `preview_paas` and `staging_paas` as environments name
when running scripts that are using API endpoint env helpers.
The environment names are temporary to avoid switching all existing
Jenkins jobs at once. `_paas` environments should be renamed to
preview and staging after the switch and the old ones can be removed.
> Add paas environments for staging and preview

- scripts/make-g-cloud-live.py
When running on Jenkins we saw over 300 services fail to publish but no useful error messages were shown.  On a subsequent run of the script locally all the failed serviced published just fine.
This adds:
* Per-service backoff so that 5 attempts will be made to publish a service that fails as the result of an API or S3 error
* Better reporting at the end of the run, showing number of published and failed services
* Exit with a non-zero status code if there were failures, so Jenkins knows to mark the build red
> Improve make-g-cloud-live script

- dmscripts/json_schema_service_faker.py
Before: Script fails to run with `AttributeError: 'module' object has no attribute 'configure_logger'`
After: Script runs OK.
> Bugfix logging import

- scripts/make-g-cloud-live.py
Running on Jenkins we're getting "'ascii' codec can't encode character..." errors.  There's not really any need to have supplier or service names in the output, as any tracking of errors will rely on IDs rather than names anyway.
> Remove service and supplier names from script output

- dmscripts/send_dos_opportunities_email.py
- dmscripts/upload_dos_opportunities_email_list.py
- requirements.txt
- scripts/send_dos_opportunities_email.py
- scripts/upload_dos_opportunities_email_list.py
- tests/test_send_dos_opportunities_email.py
- tests/test_upload_dos_opportunities_email_list.py
- Prevents existing script (`send_dos_opportunities_email`) from calling production mailchimp lists if you call the script to run against a non production environment (instead it will use a test list).
- Removes mailchimp api client functions as these have been moved into the utils library (see https://github.com/alphagov/digitalmarketplace-utils/pull/310)
- Pulls in the new DMMailChimpClient from utils and uses it instead
Trello story: https://trello.com/c/XOCeuOYW/254-update-mailchimp-user-list-everyday
- Tests will currently fail until [utils PR](https://github.com/alphagov/digitalmarketplace-utils/pull/310) has been merged
- We have not yet coded in production list ID's to our code. This will be done as the final step just so we definitely avoid running anything against production …
> Add users to mailchimp lists using the mailchimp API

- requirements.txt
The bugfixes introduced since 2.0.8 mean exceptions will not
be raised when validating email addresses that contain
apostrophes in the local part of the email address. These
are in fact valid email addresses that mailchimp accepts.
In our production database we have emails as such as we don't
want our script to fail when it tries to send them to the API.
> Bump mailchimp client to 2.0.11

- scripts/scan-g-cloud-services-for-bad-words.py
For G-Cloud 9 the `serviceSummary` key has changed to `serviceDescription`, so either should work here.
Also adds a handy counter to get a summary of all the bad words found.
> Could be serviceSummary or serviceDescription and count bad words

- scripts/get-model-data.py
CCS have requested a CSV of all current G9 services, including the service id, supplier, name of service and lot. This is so they can confirm there spend data before publishing it. The data that this will give them will allow them to cross reference against their own datasets and ensure they have the correct figures.
> Add g-cloud services to extract-model-data.py

- scripts/export-framework-applicant-details.py
This has worked with G9 for a while now, but the description still said only G8 and DOS2.
> Add G-Cloud 9 to script description

- .gitignore
- default.nix
- local.example.nix
- requirements_for_test.txt
- setup.cfg
See https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/719 for discussion of general issues.
It's a pity, but one of the dependencies I was most hoping to sort out here was `wkhtmltopdf` - but as of the nix 17.03 branch this is disabled for darwin for a couple of reasons. So for now, mac users needing generate pdfs will need to provide their own `wkhtmltopdf`. Sorry about that.
> Add default.nix

- README.md
- scripts/get-user.py
Outputs details of a random active unlocked user with a given role.
For supplier users, providing additional <framework> and <lot> arguments allows
filtering by suppliers who have published services on the given framewok and lot.
> Add a script to find a random user account

- README.md
- dmscripts/helpers/auth_helpers.py
- scripts/update-index-alias.py
Also see this PR on the Jenkins repo: [https://github.com/alphagov/digitalmarketplace-jenkins/pull/18](https://github.com/alphagov/digitalmarketplace-jenkins/pull/18)
Currently adding or moving an elasticsearch index alias is a manual job
involving constructing a bespoke request with curl.
You can do the same thing by giving this script the arguments required.
It will fetch the correct auth token for the search api from the
credentials repo.
It's being written for use by Jenkins, but could be used locally.
If invoked with `--delete-old-index=yes` it will remove whichever index
is losing the `<alias>-old`alias.
> Add script to programatically update an ES alias

- scripts/get-model-data.py
As part of this trello story - https://trello.com/c/kGVfzXuH/749-3-collect-award-status-on-buyer-dashboard - we are adding a new 'awarded' status for a brief.
This PR ensures the scripts app retains all existing functionality when this new status lands.
> Ensure existing behaviour for new 'awarded' brief status

- scripts/get-model-data.py
Third of 5 backwards compatibility PRs to handle the two new Brief statuses, `cancelled` and `unsuccessful`.
1. Admin FE alphagov/digitalmarketplace-admin-frontend#293
2. Buyer FE https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/588
3. Scripts 
4. Brief Responses FE https://github.com/alphagov/digitalmarketplace-brief-responses-frontend/pull/5
5. Briefs FE https://github.com/alphagov/digitalmarketplace-briefs-frontend/pull/17
See #137 for the equivalent changes for the awarded status.
- Adds new cancelled and unsuccessful statuses to the model query.
> Backwards compatibility for new Brief statuses

- dmscripts/models/queries.py
- scripts/get-model-data.py
- tests/models/test_queries.py
https://trello.com/c/ohWdLfJO/758-2-add-contract-info-to-data-script
Add new method `expand_json_subfields` to handle incoming json and add fields to the parent object
* Add `awardedContractStartDate` to parent `brief_response`
* Add `awardedContractValue` to parent `brief_response`
Add new fields to base model csvs
* `briefs.csv` `awardedBriefResponseId`
* `brief_responses.csv` `id,supplierOrganisationSize,awardedContractStartDate,awardedContractValue`
Test
> 758-2-add-contract-info-to-data-script

- scripts/index-services.py
- scripts/oneoff/generate-fake-g-cloud-services.py
Change default for indexing script to be g-cloud-9. We are moving away from using `g-cloud` as a the index name to use the name of the current iteration of the framework, e.g. `g-cloud-9`.
> Update indexing script to use g-cloud-9 alias

- dmscripts/notify_suppliers_of_new_questions_answers.py
If our script fails middway, we rerun it and include a specific
list of supplier IDs only to send to.  If the script fails middway
though we don't know which IDs these are as they are never logged
out. This commit will log them meaning they can be easily be
copied and pasted back into the job (from the supplier ID of
failure).
> Log list of supplier IDs that we intend to send emails to

- dmscripts/helpers/auth_helpers.py
- scripts/get-user.py
Copy/pasting the token manually (e.g. for preview or staging) increases risk of dropping it somewhere accidentally. Let's pull it in automatically. Plus it's way more convenient.
Also add a default location for the credentials repo to the `get_auth_token` method. It feels _reasonably_ safe to assume it's in the same directory as the scripts one.
It would be nice to be able to get the URL automatically but I don't think we have anything centralised to support that yet.
> Pull in token automatically

- scripts/update-index-alias.py
`es_status` has already been retrieved for the given variable.
> Remove already-derived es_status key

- README.md
- dmscripts/notify_suppliers_of_new_questions_answers.py
- tests/test_notify_suppliers_of_new_questions_answers.py
Script with description still missing:
notify-suppliers-whether-application-made-for-framework.py
> Add a description of send_dos_opportunities_email.py script to README

- .travis.yml
Yep. Let's remove Python2 tests from Travis now that scripts is Py3 compatible.
> Remove python2.7 test runner from Travis

- dmscripts/helpers/auth_helpers.py
- requirements-dev.txt
- scripts/api-clients-shell.py
- scripts/clients.py
- scripts/get-user.py
Add script to quickly access clients for dev/preview/staging; tweak scripts to build api urls automatically
Also tweaks the get-user script so you don't need to provide the api-url; you can just provide the stage.
Here for discussion.
> Clients in Python interpreter

- scripts/index-services.py
Breaking change 9 of the apiclient removed the default index name from
the search client. This made it a positional argument.
> Pass index as positional argument to search client

- requirements-app.txt
- requirements.txt
- scripts/index-to-search-service.py
- scripts/index.py
Generalize the indexer to work with briefs as well as services.
- must specify document type (`doc-type`) on command line;
- index and mapping are not updated unless `--create-with-mapping` is specified.
This is not backwards-compatible so we'll have to look at updating Jenkins jobs etc as part of planning the release for this.
https://trello.com/c/5oIKvS1s/100-search-service-for-briefs-plus-indexing-script
> Generalize the indexer for briefs

- requirements-app.txt
- requirements.txt
Allows change of API interface that won't always return link keys (alphagov/digitalmarketplace-api#693)
> Bump to API client to 14.0.1

- .flake8
- requirements-dev.txt
- scripts/make-dos-live.py
- scripts/oneoff/generate-fake-g-cloud-services.py
- scripts/scan-g-cloud-services-for-bad-words.py
- tests/test_send_dos_opportunities_email.py
This allows us to upgrade to flake8==3.5.0 which brings support for
Python 3 features like f-strings and type annotations.
Flake8 report:
```
/Users/samuelwilliams/git/digitalmarketplace-scripts/venv/bin/flake8 .
./dmscripts/__init__.py:0:1: X100 Superfluous per-file-ignores for F401
./dmscripts/helpers/__init__.py:0:1: X100 Superfluous per-file-ignores for F401
./dmscripts/models/__init__.py:0:1: X100 Superfluous per-file-ignores for F401
./scripts/bulk-upload-ccs-documents.py:31:1: E402 module level import not at top of file
./scripts/bulk-upload-ccs-documents.py:33:1: E402 module level import not at top of file
./scripts/bulk-upload-ccs-documents.py:35:1: E402 module level import not at top of file
./scripts/bulk-upload-documents.py:44:1: E402 module level import not at top of file …
```
> Change from flake8-putty to per-file-ignores

- requirements-app.txt
- requirements.txt
Addresses a vulnerability (found via Snyk alert) on the pyJWT dependency of the Notify Python client: https://nvd.nist.gov/vuln/detail/CVE-2017-11424
The Notify client has now been updated to fix the issue (https://github.com/alphagov/notifications-python-client/pull/91), this PR pulls in the new version.
> Update Notify client version for security fix

- scripts/index-to-search-service.py
Update examples to have correct mapping names (for now) and include a DOS example
> Docstring update - indexing script

- scripts/update-index-alias.py
Fix docstring as docopt interprets any line beginning with "-" as an option. As we have two lines beginning with "--delete-old-index", docopt thinks we have duplicate parameters and the script fails to run.
Discussion on docopt about it: https://github.com/docopt/docopt/issues/287
> Docstring formatted incorrectly for docopt

- scripts/snapshot-framework-stats.py
Move snapshot_framework_stats script from api to here. Tweak the script slightly to split out the get_framework_stats call as the backoff.on_exception logs the method's parameters, so if we backoff on snapshot_framework_stats then the token will get logged out. Rip out the duplicate get_api_endpoint_from_stage and use the one from dmscripts.
https://github.com/alphagov/digitalmarketplace-api/pull/733
https://github.com/alphagov/digitalmarketplace-jenkins/pull/66
https://trello.com/c/mtiS5IAx/3-move-scripts-running-python-2-on-jenkins-to-python3-docker
> Move snapshot framework stats script from api to here

- scripts/index-to-search-service.py
See https://github.com/alphagov/digitalmarketplace-search-api/pull/135 and https://trello.com/c/2wYwttWZ/171-500s-on-buyer-frontend-for-g-cloud-search-page-numbers-above-100
The api will now throw an error if attempting to create an already-existing index instead of making any attempt at updating the mapping.
> index-to-search-service.py: update --help/doc to reflect new behaviour of api

- dmscripts/export_dos_labs.py
- scripts/export-dos-labs.py
- tests/test_export_dos_labs.py
https://trello.com/c/7msYuJ6c/184-links-for-dos-labs-suppliers-not-working
I had to put up a new version of the labs spreadsheet on https://www.digitalmarketplace.service.gov.uk/buyers/frameworks/digital-outcomes-and-specialists-2/requirements/user-research-studios
I used this script (which I assumed was how it was done in the past). I had to do a bunch of manual formatting to make it look pretty for an end user. I will details of this to the manual in the framework lifecycle section.
> Include supplier contact details for dos labs export

- dmscripts/bulk_upload_documents.py
- dmscripts/upload_counterpart_agreements.py
- tests/test_bulk_upload_documents.py
- tests/test_upload_counterpart_agreements.py
Because we now log in to S3 using IAM roles inherited from other accounts, files uploaded as 'private' can not be viewed by developers logged in to the console.
Using 'bucket-owner-full-control' rather than 'private' means that devs will be able to view and modify documents in the S3 console.
> Use 'bucket-owner-full-control' instead of 'private' ACL

- scripts/index-to-search-service.py
trivial PR huh...
- without this, docopt doesn't give you a way to see the options.
> Add missing help option.

- scripts/oneoff/rename-supplier-registered-country.py
Part of this trello card: https://trello.com/c/FeBysBI7
Currently suppliers that are registered in the UK have the string 'gb'
set in the `registration_country` field of the suppliers table.
As part of the new supplier sign up flow we're going to be collecting
their registration country via the country picker supplied by registers.
We need to bring our existing data in line with the data the country
picker will be supplying.
> Add one-off script for renaming supplier registration country

- dmscripts/notify_suppliers_of_awarded_briefs.py
- requirements-app.txt
- requirements.txt
- scripts/notify-suppliers-of-awarded-briefs.py
- tests/test_notify_suppliers_of_awarded_briefs.py
This script will run overnight to collate all brief responses awarded the previous day and notify them by email
https://trello.com/c/LsEbL3jP/306-send-dos-suppliers-an-email-to-let-them-know-the-outcome
> Notify suppliers when a brief has been awarded

- scripts/notify-suppliers-of-awarded-briefs.py
Trello: https://trello.com/c/LsEbL3jP/306-send-dos-suppliers-an-email-to-let-them-know-the-outcome
(Hit merge too quickly on the previous PR!)
We should add 'consistent usage for docopt options/params' to the list of things to sort out for our scripts.
> Fix docopt options for Notify Suppliers of awarded Briefs script

- dmscripts/notify_suppliers_of_awarded_briefs.py
- requirements-app.txt
- requirements.txt
- tests/test_notify_suppliers_of_awarded_briefs.py
Trello: https://trello.com/c/LsEbL3jP/306-send-dos-suppliers-an-email-to-let-them-know-the-outcome
Extends the script to include Briefs that were marked as `unsuccessful` or `cancelled` on the same date. This means an extra query to the `/briefs` endpoint to get all briefs for those statuses (there shouldn't be many - currently less than 10 each since Oct 2017), then filtering those Briefs by date within the script. We then get the associated Brief Responses for those briefs as normal.
Retrying the script with the list of IDs should be unaffected.
> Notify suppliers for cancelled and unsuccessful Briefs

- dmscripts/notify_buyers_when_requirements_close.py
Because we now have 3 different methods of sending emails we should update utils to ensure `send_email` is imported from the client specific sub-directory of emails in utils
> Update import to import send_email from dm_mandrill

- scripts/oneoff/migrate-supplier-trading-status.py
One-off script for migrating suppliers existing trading status
(submitted during framework applications) to our new set of values now
that this is an account-level question. If we can map it perfectly
across, we'll do so, but if we can't then we'll drop the value
altogether - the result of this being the supplier will need to provide
it again.
At the moment, the idea behind this (dropping values that we can't map correctly) doesn't work as the API requires a value to be submitted. I don't know how I feel about coercing values to 'other' rather than None, so open to input here. If we decide to go ahead with this script as-is, we'll need to change validation (probably just temporarily), or do some other magic.
https://trello.com/c/Wvvtb1yW/52-new-editable-page-trading-status
> Migrate supplier trading status

- scripts/oneoff/migrate-supplier-organisation-size-from-declarations.py
Prep work needed for https://trello.com/c/PZyZdMtG/337-custom-dimension-to-capture-size-of-supplier
As this is a one-off script this hopefully won't need tests, but I can add them if necessary 😄 
I've adapted the `migrate-supplier-data-from-declarations` script to just update one supplier field, `organisation_size` (the retry/backoff stuff is all copied from that script). 
For each supplier, we get the list of their frameworks and choose the most recent non-null declaration to get the `organisationSize` from.
Running this locally took around 8 minutes, I'd expect slightly longer on preview.
> One off script for migrating supplier organisation size

- dmscripts/export_framework_applicant_details.py
This script is often used to contact the supplier in question about their declaration or application.
We should include the proper contact details for the supplier.
> This csv should contain the contact details of the supplier in question

- requirements-app.txt
- requirements.txt
This is to pull in this update to the utils - https://github.com/alphagov/digitalmarketplace-utils/pull/365
We're pulling in the updated Mailchimp client which should mitigate timeouts when fetching email lists from Mailchimp.
All of the major versions don't affect the scripts repo.
Once this is merged the scripts docker image will need rebuilding and pushing up to Dockerhub.
> Fix timeouts when calling Mailchimp

- dmscripts/generate_questions_csv.py
The 'b' modifier on the delimiters don't work with Python 3.  Also added using the current working directory as the default directory to create the csv file in, for if the full path isn't specified on the command line.
> Fix "generate-questions" script for Python 3

- README.md
- requirements-app.txt
- requirements.txt
- scripts/virus-scan-s3-bucket.py
A small script which streams objects from s3 to a clamd server.
https://trello.com/c/i30jDD69/317-automatically-virus-scan-uploaded-files-framework-agreements
> Add clamd s3 virus scanner

- dmscripts/upload_dos_opportunities_email_list.py
- requirements-app.txt
- requirements.txt
- tests/test_upload_dos_opportunities_email_list.py
Pull in latest dm-utils which updates the MailChimp client to use a
generator and have a smaller page size when retrieving email addresses
from an existing list, which should hopefully result in fewer 504
timeouts with MailChimp servers.
https://trello.com/c/4cK1wTvq/236
> Update utils for MailChimp client

- scripts/upload-counterpart-agreements.py
Some of the scripts are still trying to use the `boto` library. dm-utils
has been updated to use boto3 and create its own S3ResponseError, so
let's update this to do the same.
> boto to boto3

- scripts/maintenance-mode-pr.sh
Adds a script to create a Pull Request on the dm-aws repository which
toggles maintenance mode on/off for a specific environment, in the same
vein as the script for rotating API tokens. Not ready to generalise this
script yet - but if we add another job that manages Pull Requests we
should review and see what can be taken out and centralised.
https://trello.com/c/XKISVVf1/422-create-jenkins-job-to-turn-on-off-maintenance-mode
> Create maintenance mode PR

- scripts/oneoff/reset-supplier-declaration.py
If suppliers were affected by not being able to copy their answers from
G-Cloud 9, we need to reset their declaration so that they have to click
'Start declaration' again, at which point they will get the opportunity
to re-use answers from G9.
> Add script for resetting supplier declaration

- requirements-app.txt
- requirements.txt
The new utils has a fix for a bug in the DM Mailchimp client. It'll
catch and handle errors if a response has malformed or missing json
data. See here:
https://github.com/alphagov/digitalmarketplace-utils/pull/390
The Notify client has a fix for issues installing with pip v10.
Interestingly their internal tagging script has an issue which means
that installing 4.8.2 directly from Github won't work. We can instead
install from PyPI though.
> Bump utils to 36.7.0 and notify client to 4.8.2

- requirements-app.txt
- requirements.txt
- scripts/oneoff/inject-framework-dates.py
We are going to retire the `dates.yml` file from the
digitalmarketplace-frameworks repository in favour of storing this
information in the Framework model on the API. This script will inject
all the appropriate datetime information into existing framework
records.
https://trello.com/c/BVPgZRZc/65-store-datetimes-relating-to-the-framework-lifecycle-on-the-api
> Inject framework dates

- dmscripts/helpers/supplier_data_helpers.py
- requirements-app.txt
- requirements.txt
- scripts/notify-suppliers-whether-application-made-for-framework.py
We don't need to pass the `successful notification date` in any more as
this is now stored on the API. It is called the `intention to award at`
date there, so we'll update references to keep language consistent.
I'll update the two Notify templates using this personalisation when
this PR is merged.
> Update notify suppliers script

- dmscripts/generate_framework_master_csv.py
We now inject company details into the supplier framework when a
framework changes from open to pending. This means that suppliers who
haven't started a declaration no longer have a 'False-y' declaration if
they haven't answered any questions, so we need to do a `get('status')`
rather than a direct `['status']` on the dict.
> Update generate framework master csv

- scripts/virus-scan-s3-bucket.py
We only need timestamps if we're scanning files modified from a certain
date. Loading timestamps can take some time.
> Virus scanner - only load timestamps if !!'since'

- .dockerignore
- Dockerfile
- README.md
- docker_for_mac_entrypoint.sh
Ticket: [Trello](https://trello.com/c/R5tAKXEA/301-testing-dm-scripts-against-local-environment-within-the-docker-container-is-broken)
This is useful for macOS development environments, if services are
running on the host machine they are not normally accessible to the
container.
This commit adds a script `docker_for_mac_entrypoint.sh`, that
forwards the ports within the container transparently to the Docker
host, so that the API services can be accessed as if they were
running within the container.
By default the entrypoint is not used; it is copied into PATH in the
container but must be enabled when `docker run` is called. An
explanation of how to do this has been added to the readme file.
> Add an entrypoint to forward API ports from Docker

- dmscripts/helpers/email_helpers.py
- dmscripts/notify_buyers_to_award_closed_briefs.py
- scripts/notify-successful-suppliers-for-framework.py
- scripts/notify-suppliers-of-awarded-briefs.py
- scripts/notify-suppliers-of-brief-withdrawal.py
- scripts/notify-suppliers-whether-application-made-for-framework.py
- scripts/upload-counterpart-agreements.py
- tests/test_notify_buyers_to_award_closed_briefs.py
We send a lot of fake emails with scripts that run against preview.
Doing this regularly and repeatedly will degrade Notify's reputation
with its email provider, so we need to stop sending emails to addresses
that we know are bad. We should make a concerted effort to stop doing
this wherever possible.
This is an alternative to centralising the email redirects in utils as
put forward in
https://github.com/alphagov/digitalmarketplace-utils/pull/405.
https://trello.com/c/YIJ25eiP/479
> Redirect Notify emails in scripts

- dmscripts/helpers/email_helpers.py
https://ci.marketplace.team/job/notify-buyers-to-award-closed-briefs-4-weeks-production/240/consoleFull
broke because the partial invocation was bad (returns a callable, but
wasn't calling it).  This fixes it.
> Fix scripts notify helper

- scripts/make-g-cloud-live.py
- scripts/upload-counterpart-agreements.py
See these associated PRs:
https://github.com/alphagov/digitalmarketplace-aws/pull/403
https://github.com/alphagov/digitalmarketplace-credentials/pull/119
https://github.com/alphagov/digitalmarketplace-jenkins/pull/90
Some scripts on Jenkins were using a config file for creds when they
should use the jenkins role instead.
> Update docstrings of scripts that use aws on Jenkins

- scripts/update-framework-results.py
We have an auth token helper that means we shouldn't need to pass tokens
in on the command line. Let's use this here.
Not doing all files as I am just focused on this script at the moment. Other files are out of scope.
> Don't pass auth token on cmd line

- dmscripts/bulk_upload_documents.py
- dmscripts/generate_framework_agreement_signature_pages.py
- scripts/generate-framework-agreement-counterpart-signature-pages.py
- templates/framework_signature_page/framework-agreement-signature-page.html
Updates the countersigned framework agreement page generator to use the
new templates in the scripts directory and take a path to the signature
image stored in credentials.
Need to read the file in binary mode or Python3 complains about utf-8
decoding errors.
> Update scripts for G10 standstill

- dmscripts/helpers/auth_helpers.py
Jenkins stores tokens for jobs in DM_DATA_API_TOKEN_\<stage\> and
DM_SEARCH_API_TOKEN_\<stage\>, so our auth helper is looking in the wrong
place. Fix this by prefixing 'data-' and casting '-' to '_'.
> Build correct env var name for Jenkins

- dmscripts/upload_counterpart_agreements.py
- scripts/upload-counterpart-agreements.py
We need to check the declaration for the presence of two keys in order
to support old and new framework iterations: supplierRegisteredName (G10
and onwards) and nameOfOrganisation (DOS2 and older).
Also updates the upload-counterpart-signatures.py script to derive the
api token from the environment.
> Check for correct keys in declaration

- dmscripts/upload_counterpart_agreements.py
We are uploading PDFs to S3 so need to open the file in binary mode or
S3 complains about trying to decode it as UTF-8.
> Open file in binary mode for upload

- dmscripts/export_framework_applicant_details.py
- dmscripts/helpers/supplier_data_helpers.py
- requirements-app.txt
- requirements-dev.txt
- requirements.txt
- tests/conftest.py
- tests/helpers/test_supplier_data_helpers.py
We store supplier country details in the database as country codes that
relate to a Country or Territory Register. These are not intended for
human consumption, so we should convert these back to the proper
representation of the country (e.g. `country:GB` -> `United Kingdom`),
otherwise we need to do this manually before sharing the data with our
partners (e.g. CCS).
https://trello.com/c/bx6MXS0V/173
> Convert country codes to names

- README.md
- scripts/publish-dos-draft-services.py
- scripts/publish-g-cloud-draft-services.py
The script names were a little confusing and implied that they actually
made the framework 'live'. They actually just promote draft-services
into "real" services.
> Rename `make-<framework-family>-live` scripts

- scripts/oneoff/acknowledge_publish_draft_service_updates.py
When moving G-Cloud 10 services from drafts to 'published', we generate
a lot of `update_service` audit events. We have an admin page that
allows CCS to review and acknowledge `update_service` audit events, but
this is only intended for services which are currently live (i.e. the
framework is open). Service changes from the script which promotes the
drafts, `publish-g-cloud-draft-services.py` (and
`publish-dos-draft-services.py`) should not need to be acknowledged by
CCS.
This script will go through and acknowledge all audit events created by
the publishing scripts.
> Acknowledge draft service updates

- scripts/publish-g-cloud-draft-services.py
If the document has already been copied across for a service, ignore the
error and continue - in case other documents haven't been copied across.
> Ignore s3 key already exists

- requirements-app.txt
- requirements.txt
- scripts/data-retention-remove-contact-information-data.py
- scripts/data-retention-remove-user-data.py
** Requires alphagov/digitalmarketplace-apiclient#142 **
** Requires https://github.com/alphagov/digitalmarketplace-api/pull/802 **
* Brings in new `apiclient` version
* Adds `scripts/data-retention-remove-user-data.py`
* If the users last login was greater than 3 * 365 days ago then remove the personal data using the `apiclient` methods that use the new `api` views
* verbosity and dryrun options
* Adds `scripts/data-retention-remove-contact-information-data.py`
* If all users of a supplier have had their personal data removed then remove the personal data from that supplier
> 208 delete users code that takes the user and strips all the personal data out

- scripts/oneoff/fix_accidentially_published_g10_services.sql
Some services where published accidentally for G10 that belonged to
suppliers who didn't make it on to the framework.
This reverts the mistake and adds audit events manually as a record.
> Add SQL script to fix accidentally published services

- scripts/publish-g-cloud-draft-services.py
When specifying a list of draft IDs to publish, we still need to make
sure we can only publish drafts from suppliers that are actually on the
framework.
> Only publish for suppliers on framework

- scripts/generate-successful-suppliers-for-framework-csv.py
When a framework goes live we need to produce a CSV file of all the
suppliers that were successfully awarded onto the framework and all the
lots they were successful on. This is then uploaded to the frameworks
communications updates page. At the moment I guess this was done
manually, as I can't see a script that produces this file.
So now we have one.
https://trello.com/c/aGxhSBwa/150
> Add script for successful suppliers csv

- dmscripts/send_stats_to_performance_platform.py
- scripts/send-stats-to-performance-platform.py
- tests/test_send_stats_to_performance_platform.py
Trello https://trello.com/c/GE3VaURm/95-get-performance-platform-dashboard-for-dos3
Decided to make this an optional parameter defaulting to "gcloud" for backwards compatibility - should be mergeable without a synchronized jenkins update.
> send-stats-to-performance-platform: allow configurable pp "service" name

- dmscripts/helpers/auth_helpers.py
When running scripts in Docker, the credentials repo and SOPS are not available.
If the user forgets to expose the api token environment variable (like I did, today 😱), they will get confusing errors about SOPS not being available, when really the error should be that the api token is not available in the environment.
As we are going to be running scripts in Docker from now on, this sops code is dead, and so I have replaced it with a helpful error message.
> Remove code that relies on sops/credentials repo

- dmscripts/send_stats_to_performance_platform.py
in calls to `send_by_stage_stats` & `send_by_lot_stats`
> send-stats-to-performance-platform: remember to include pp_service arg

- dmscripts/notify_suppliers_of_brief_withdrawal.py
- dmscripts/notify_suppliers_of_new_questions_answers.py
- tests/test_notify_suppliers_of_brief_withdrawal.py
- tests/test_notify_suppliers_of_new_questions_answers.py
Trello: https://trello.com/c/R3DsCXFa/22-use-frameworkfamily-frameworkfamily-in-apps-apiclient-rather-than-frameworkframework-frameworkframework
Two scripts updated to use the nested `framework.family` instead of `frameworkFramework`.
> Use framework.family instead of frameworkFramework

- scripts/notify-buyers-when-requirements-close.py
Trello: https://trello.com/c/XJEqu5gI/15-spike-audit-tokens-used-by-jenkins-jobs
Use the `get_auth_token` helper to fetch the API token for the relevant stage. 
**Do not merge yet** as the corresponding Jenkins job needs to be updated first to remove the old argument (see https://github.com/alphagov/digitalmarketplace-jenkins/pull/106).
> Convert scripts to use environment var for api token

- dmscripts/helpers/auth_helpers.py
This reverts commit 3e7b1ae9c6bd4201bb6d40ce84e6983cb2358d42.
This code is used when running scripts locally, such as
`scripts/api-clients-shell.py` and `scripts/get-user.py`
> Revert "Remove code that relies on sops/credentials repo"

- dmscripts/export_framework_applicant_details.py
These questions were not asked as part of the DOS3 declaration, and as
such should not be included. They just generate two empty columns.
> Remove cyber fields for DOS3 from export applicants script

- scripts/rotate-api-tokens.sh
Ticket: https://trello.com/c/eBl3yUUT/27-jenkins-credentials-shown-in-plain-text-in-job-scripts-and-logs
rotate-api-tokens.sh uses a GitHub API token to get the digitalmarketplace-credentials repo; however when a push is made the token is echoed to the screen, which means it will end up in all sorts of logs.
This commit adds the quiet flag to the push so that it will only echo if there is an issue.
Note that this means the API token will be leaked if there is an issue with the push.
> Prevent github api token from being echoed in rotate api tokens script

- Dockerfile
Change the base image to be the latest 3.6 image available in the official Python repository
Closes https://trello.com/c/clauyQUN/121-update-docker-base-image-for-digitalmarketplace-scripts
> Update Dockerfile to use latest Python 3.6 image

- dmscripts/index_to_search_service.py
- scripts/index-to-search-service.py
- tests/test_index_to_search_service.py
Prep for https://trello.com/c/KzDlJAcH/125-prevent-indexing-script-using-wrong-mapping-file
Our main indexing script is untested 🙀. This PR should have no functional changes at all. I've run it locally for briefs and services and it seems fine, but not against Preview yet. Perhaps you, the reviewer, would like to give it a go...
- Moves logic out of top level script
- Adds tests for `do_index` (the main function) and the major class methods
- Some weird patching of the two API clients was needed as *I didn't want to change the code or the docopt stuff at all*. Normally in scripts we initialise the clients at the top level then pass the instance through to the script function, but here we initialise within the script function itself. So instead of just using a mock object as the client …
> Add tests for indexing script

- dmscripts/index_to_search_service.py
- tests/test_index_to_search_service.py
Trello: https://trello.com/c/KzDlJAcH/125-prevent-indexing-script-using-wrong-mapping-file
The aim: to sanity check that we're using the right mapping file when creating an index for a framework.
The problem: as the index doesn't exist yet, we don't 'know' what mapping to use. 
The compromise: given we are unlikely to support frameworks other than G-Cloud/DOS in the near future, we can hardcode a dictionary of frameworks and their mappings for now. We can manually look at the Search API's `/g-cloud-10` or `/briefs-digital-outcomes-and-specialists` endpoints (see https://github.com/alphagov/digitalmarketplace-search-api/pull/163) to sanity check what mapping was used to create those indexes.
> Check mapping dict for matching framework before creating index

- dmscripts/notify_suppliers_of_awarded_briefs.py
- requirements-app.txt
- requirements.txt
In some cases users have multiple email addresses in their respondToEmailAddress field.
This causes errors in the "Notify suppliers of awarded briefs" script (see [this ticket](https://trello.com/c/DHDgBuns)).
This PR adds a limited ability to handle strings where there are multiple email addresses separated by a character such as `;` or `/`.
See alphagov/digitalmarketplace-utils#450 for more details on the helper functions used.
This PR only modifies the one script, as that is the only one I've seen having this error. We can extend it to other scripts with a little effort; unfortunately all the scripts seem to be written in slightly different ways without much reuse.
Additionally, I removed Flask-FeatureFlags from the requirements file as I upgraded to `dmutils 43.x.x`. I also upgraded …
> Handle multiple email addresses in Notify suppliers of awarded briefs script

- requirements-app.txt
- requirements.txt
dmutils 43.4.0 uses space as an email separator by default
> Add support for space as separator of multiple email addresses

- dmscripts/mark_definite_framework_results.py
- scripts/mark-definite-framework-results.py
If you're reassessing, you may only want to assess certain suppliers.
> Allow mark_definite_framework_results to take supplier id list

- dmscripts/generate_supplier_user_csv.py
- scripts/generate-supplier-user-csv.py
- tests/test_generate_supplier_user_csv.py
Trello: https://trello.com/c/FtV7sVMU/138-admin-download-all-suppliers-for-framework-endpoint-locks-up-an-api-process
Fetches supplier/user data from the API, creates a CSV (saving to a local `data` folder by default, as per the `get-model-export.py` script) then uploads that file to S3. 
There are 3 different CSV files that could be generated by this script:
1. Official supplier details for a framework
2. Supplier user contact details for a framework (all active users)
3. Supplier user contact details for a framework (user research opted-in only)
Examples:
```
./scripts/generate-supplier-user-csv.py preview suppliers g-cloud-10
./scripts/generate-supplier-user-csv.py preview users g-cloud-10 --dry-run
./scripts/generate-supplier-user-csv.py preview users g-cloud-10 …
```
> Export suppliers/users to CSV scripts

- dmscripts/index_to_search_service.py
- dmscripts/send_stats_to_performance_platform.py
- requirements-app.txt
- requirements.txt
- scripts/oneoff/acknowledge_publish_draft_service_updates.py
- scripts/oneoff/migrate-supplier-data-from-declarations.py
- scripts/oneoff/migrate-supplier-organisation-size-from-declarations.py
- scripts/oneoff/migrate-supplier-trading-status.py
- scripts/oneoff/rename-supplier-registered-country.py
- scripts/publish-g-cloud-draft-services.py
- scripts/snapshot-framework-stats.py
- tests/helpers/test_framework_helpers.py
- tests/test_insert_framework_results.py
I had an issue the other day where I couldn't use one of the new API features in the `api-clients-shell` environment, because the apiclient in scripts was outdated. This PR updates the apiclient version specified in the requirements file. 
There was one breaking change that I did fix, and another that I didn't, as it only affected some one-off scripts that seemed not very important.
> Update apiclient (16.x.x -> 19.x.x)

- dmscripts/generate_framework_agreement_signature_pages.py
If a suppliers application is marked as discretionary we shouldn't
create a signature page for them.
> Don't generate signature pages for discretionary applications

- dmscripts/generate_supplier_user_csv.py
- tests/test_generate_supplier_user_csv.py
Trello: https://trello.com/c/FtV7sVMU/138-admin-download-all-suppliers-for-framework-endpoint-locks-up-an-api-process
In order to serve the S3 file in the admin (via the `DM_ASSETS_URL`), the router needs to proxy the url to the correct bucket. To do that, it uses a regex to match the path supplied (see https://github.com/alphagov/digitalmarketplace-router/pull/30/files). The other asset buckets include their type in the path structure to assist with this (e.g. `/g-cloud-10/communications/filename.csv`), and the reports bucket should do the same.
TL;DR - this PR sticks a `.../reports/...` in the CSV upload path.
Tested against preview already, works as expected.
> Include reports folder in S3 upload path

- dmscripts/send_dos_opportunities_email.py
- tests/test_send_dos_opportunities_email.py
For [this trello ticket.](https://trello.com/c/FMcdroGN)
Content has been checked with Tracy and Constance.
The script to send suppliers information about newly released dos
opportunities had the framework name hardcoded into the subject line for
the mailchimp campaign. This was an issue as there is a chance that
we'll have new briefs from two different iterations when we transition
from DOS2 to DOS3.
This grabs the iteration from the live briefs found and formats the
subject line. It also means we don't have to worry about updating the
script after DOS3 goes live.
> Remove hard coded framework from send_dos_opportunities

- dmscripts/send_dos_opportunities_email.py
- scripts/send-dos-opportunities-email.py
- scripts/upload-dos-opportunities-email-list.py
- tests/test_send_dos_opportunities_email.py
For [this trello ticket](https://trello.com/c/y3Rv3kGC).
This will require updates to the Jenkins jobs which run these scripts. Coming next.
We're going to need a new list for DOS3 suppliers. Being able to select
framework specific list ids will make the transition from dos2 to dos3
much easier.
The list IDs for DOS3 have already been created in Mailchimp.
And pass framework_slug to main.
We need to send separate emails to separate lists based on which DOS
opportunities are available.
> Update scripts that manage and send DOS3 opportunity emails

- dmscripts/generate_supplier_user_csv.py
- tests/test_generate_supplier_user_csv.py
Trello: https://trello.com/c/FtV7sVMU/138-admin-download-all-suppliers-for-framework-endpoint-locks-up-an-api-process
The objects uploaded to the S3 reports buckets need to have `acl='bucket-owner-full-control` so that the `paas-app-user` can access and download the files.
> Change acl for uploaded reports

- dmscripts/notify_buyers_when_requirements_close.py
- dmscripts/notify_suppliers_of_new_questions_answers.py
- tests/test_notify_buyers_when_requirements_close.py
- tests/test_notify_suppliers_of_new_questions_answers.py
This PR fixes some careless mistakes on my behalf.
I've made sure now that the send_email is patched with autospec so that the proper call signature is checked by tests, and I also actually ran these on my machine this time, which I foolishly neglected to do last time.
> Fix bugs in ported email scripts

- dmscripts/get_user.py
- dmscripts/helpers/framework_helpers.py
- dmscripts/helpers/user_helpers.py
- scripts/get-user.py
This commit adds a function to `scripts/get-user.py` that searches for a buyer with published briefs. I needed this to test a bit of functionality I was working on and thought it might be useful for other people.
I also took the opportunity to refactor the script, moving the logic out into modules.
> Add search for buyer with briefs to get-user script

- Makefile
- default.nix
- dmscripts/virus_scan_s3_bucket.py
- requirements-app.txt
- requirements.txt
- scripts/virus-scan-s3-bucket.py
- tests/test_virus_scan_s3_bucket.py
https://trello.com/c/aWnL8fAa/192-antivirus-create-catch-up-bulk-scan-script
This ports the script `virus-scan-s3-bucket.py` to use the antivirus api for actual scanning of objects. It will allow us to scan & tag all existing files on a bucket and will also be good to use as a "catch up" script which runs periodically and scans any file versions which missed SNS-triggered scanning for some reason.
There are a number of things that should(/could?) be done to this before we say it's done:
- Add tests, obviously. This may need some preparatory work as the test will presumably use `moto` which isn't yet a dependency of this repo. And because this will be the third place I'd be copypasta-ing basically the same `moto`-based pytest fixtures, it feels like time to stick them together - possibly …
> Antivirus scanning script

- dmscripts/virus_scan_s3_bucket.py
- scripts/virus-scan-s3-bucket.py
- tests/test_virus_scan_s3_bucket.py
https://trello.com/c/aWnL8fAa/192-antivirus-create-catch-up-bulk-scan-script
@lfdebrux alerted me that integer increment in python is indeed *not* atomic. So instead don't try to be such a smartass in the file counting and instead pass the counts in the map function results and accumulate in the loop...
> virus_scan_s3_bucket: don't try to be so clever in counting

- requirements-app.txt
- requirements.txt
- scripts/virus-scan-s3-bucket.py
https://trello.com/c/ZSg7FK5s/201-switch-av-api-scanandtags3object-endpoint-to-put-was-apiclient-sort-out-timeouts-retrying-once-for-all
This causes the `virus-scan-s3-bucket.py` script to use `PUT` requests which should add reliability.
> digitalmarketplace-apiclient dependency: bump to v19.7.0

- dmscripts/virus_scan_s3_bucket.py
- scripts/virus-scan-s3-bucket.py
- tests/test_virus_scan_s3_bucket.py
https://trello.com/c/aWnL8fAa/192-antivirus-create-catch-up-bulk-scan-script
This is because we'll probably want to scan all an environment's buckets in a single jenkins job and writing the loop in python is nicer than writing it in bash.
Tests getting more complex though.
> virus_scan_s3_bucket: add support for scanning multiple buckets in one call

- dmscripts/virus_scan_s3_bucket.py
- scripts/virus-scan-s3-bucket.py
- tests/test_virus_scan_s3_bucket.py
https://trello.com/c/eI2PEVIY/202-create-jenkins-job-for-virus-scanning-catchup-script
Script counterpart to https://github.com/alphagov/digitalmarketplace-antivirus-api/pull/19
> virus_scan_s3_bucket: handle 4xx errors from antivirus-api, counting them & continuing

- requirements.txt
ItsDangerous==1.0.0 was pulled from PyPI which makes this version of digitalmarketplace-scripts fail when `make requirements` is run.
As various parts of our infrastructure rely on scripts we need to revert to the last available version of ItsDangerous.
As of now there is a 1.1.0 version of ItsDangerous available, however for stability it is preferable to use the tried and tested version.
> Revert ItsDangerous version bump

- dmscripts/get_user.py
- dmscripts/helpers/auth_helpers.py
- scripts/api-clients-shell.py
- scripts/clients.py
- scripts/oneoff/acknowledge_publish_draft_service_updates.py
- scripts/oneoff/inject-framework-dates.py
- scripts/oneoff/reset-supplier-declaration.py
See https://github.com/alphagov/digitalmarketplace-scripts/issues/257
(I've had this Issue tab open in my browser for months and it's starting to annoy me - just this and one more branch to tick off, then we can close it)
- Utils has a function to construct API urls for each stage (including local/dev). See https://github.com/alphagov/digitalmarketplace-utils/blob/master/dmutils/env_helpers.py
- Scripts certainly doesn't need its own function to do this
- Most of the scripts already use the utils function; this PR cleans up the remaining scripts and deletes the function
> Use utils api endpoint helper

- scripts/publish-g-cloud-draft-services.py
Since we last published G-Cloud documents we've changed our S3 module
and documents now get a default acl of 'private'. We need to override
this.
Also adds some info to the docstring about object owners.
> Give published documents 'public-read' acl

- dmscripts/data_retention_remove_supplier_declarations.py
- dmscripts/helpers/supplier_data_helpers.py
- scripts/data-retention-remove-failed-suppliers-declarations.py
- tests/helpers/test_supplier_data_helpers.py
This script builds pretty heavily on some work I've already done. It offers a script to remove declarations from the suppliers who failed to get onto a framework.
The script is called and the framework passed as an argument. It then finds all the suppliers that applied, identifies the ones who didn't make it on, and then deletes their declaration for that particular framework.
It does the filtering locally, in memory, because there doesn't seem to be an api method for finding unsuccessful suppliers. This is obviously inefficient at scale, and we estimate there's approximately 4,000 applicants per framework. However, I don't think committing more time into developing a new method is an efficient use of our time. 
[Here's a Trello card](https://trello.com/c/yOHN6iUB/3-deleting-declarations-o …
> Delete unsuccessful suppliers declarations

- README.md
Adds a nifty visual indicator of what versions of Python we support
Part of https://trello.com/c/wWFsv1SU/230-be-clear-in-our-libraries-what-versions-of-python-we-support
> Add Python badge to README

- aws-auth.nix
- default.nix
> default.nix: add self-contained aws-auth.nix now that it is removed from nixpkgs

- dmscripts/data_retention_remove_user_data.py
- requirements-app.txt
- requirements.txt
- scripts/data-retention-remove-user-data.py
- tests/test_data_retention_remove_user_data.py
More thoughts here https://trello.com/c/QROOUpoX/272-users-whose-personal-data-is-removed-are-not-removed-from-mailchimp-mailing-lists
Also, refactor into separate implementation function for easy testing, add simple tests.
Depends on https://github.com/alphagov/digitalmarketplace-utils/pull/483
> data-retention-remove-user-data: make this also check mailchimp mailing list membership

- dmscripts/data_retention_remove_user_data.py
- tests/test_data_retention_remove_user_data.py
https://trello.com/c/QROOUpoX/272-users-whose-personal-data-is-removed-are-not-removed-from-mailchimp-mailing-lists
Because succeeding in removing a users personal data from the API will cause their email address to be scrubbed, if we make removing the data from the API the *first* thing we attempt to do, we will only give ourselves one chance to remove the address from mailchimp, because a subsequent run of the script won't have access to the email address in question anymore.
Simple fix is to attempt the mailchimp removal first and ensure we don't then continue on to remove a user from the API db if we haven't been able to remove them from mailchimp.
The loud failure should spur one of us to do something about it or reconsider how we should handle this.
Also note, for similar reasons we …
> data_retention_remove_user_data: tweak to make less likely we shoot selves in foot

- scripts/data-retention-remove-user-data.py
If these arguments are not passed to the script they don't appear in the args dict causing a KeyError
> Check existence of args and value

- dmscripts/export_framework_applicant_details.py
- dmscripts/export_framework_results_reasons.py
- dmscripts/generate_buyer_email_list.py
- dmscripts/helpers/framework_helpers.py
- scripts/export-dos-labs.py
- scripts/export-dos-outcomes.py
- scripts/export-dos-participants.py
- scripts/export-dos-specialists.py
- scripts/export-framework-applicant-details.py
- scripts/export-framework-results-reasons.py
- scripts/generate-buyer-email-list.py
- scripts/generate-framework-agreement-signature-pages.py
Stumbled upon this while trying to get the test suite to pass for https://github.com/alphagov/digitalmarketplace-scripts/pull/320 instead of deadlocking on unrelated tests.
This way different implementations can be supplied on invocation and e.g. we can call each in single threaded mode by supplying the builtin `map`, which is also used as the default argument everywhere so these functions can still be called from anywhere without worrying about the map implementation and still get a safe result.
This is particularly useful for tests, where running the code in multithreaded mode complicates things and can even cause deadlocks if an instance of `mock.Mock` is shared among several threads.
Something I'm a little nervous of with this is that we obviously don't have test coverage of the …
> threading: make all uses of multithreaded map do so through dependency injection

- requirements-app.txt
- requirements.txt
Bring in changes from https://github.com/alphagov/digitalmarketplace-utils/pull/484
> Update utils (45.3.0 > 45.3.1) to use new mailchimp3 version

- dmscripts/send_dos_opportunities_email.py
We were getting duplicated log output when running the `send-dos-opportunities-emails.py` script.
This commit fixes this by removing the logging configuration from the `send_dos_opportunities_emails.py` module, which was causing multiple logs with the same contents to exist.
Closes https://trello.com/c/u18CsU00/313-statements-are-logged-twice-on-jenkins-during-dos-opportunities-mailchimp-job
> Fix duplicate logging output from send_dos_opportunitues_emails

- dmscripts/data_retention_remove_user_data.py
- tests/test_data_retention_remove_user_data.py
Another stupidity I've realized related to my implementation of https://trello.com/c/QROOUpoX
If `user["personalDataRemoved"]`, then the `emailAddress` we're given will already be garbage and looking it up in mailchimp is meaningless.
> data_retention_remove_user_data: don't attempt to remove users from mailchimp if already personalDataRemoved

- dmscripts/models/modeltrawler.py
- scripts/get-model-data.py
- tests/models/test_modeltrawler.py
https://trello.com/c/t2N1EqPk/
This required changing the way column headers are generated from "nested fields". Previously the innermost field name of a chain would be picked, but this is vulnerable to clashes, as will happen when multiple nested dictionaries with `id` attributes are desired. The change is to `.`-concatenate the field names. The only effect this should have on existing exports is changing one header in `briefs.csv` from `emailAddress` to `users.0.emailAddress`. Ash reckons this shouldn't break any of his stuff but we're going to make sure with a dry run from a local machine before merging.
> get-model-data: add "completed outcomes" export

- dmscripts/export_framework_results_reasons.py
- dmscripts/mark_definite_framework_results.py
- scripts/export-framework-results-reasons.py
- scripts/mark-definite-framework-results.py
- tests/test_mark_definite_framework_results.py
Simplify script
Avoid extraneous/ confusing initialisation of service_counter
Add more comments
Makes the script a bit more verbose but I think more readable. I've annotated each of the pass/ fail conditions with a comment saying what we're checking for and what that results in.
> simplify-mark-framework-results-script

- Dockerfile
The Dockerfile for digitalmarketplace-scripts currently fetches some binary dependencies from an s3 bucket managed by us. This means we are responsible for keeping these binaries up-to-date, which is a big pain.
A simpler method is to fetch the binaries from the GitHub release page; although we are still responsible for keeping the packages up-to-date, at least this way we don't have to log in to AWS ;)
> Don't fetch binaries from s3

- scripts/rotate-api-tokens.sh
I think this is the cause of the incorrectly-generated PR https://github.com/alphagov/digitalmarketplace-credentials/pull/191
> rotate-api-tokens.sh: make get_jenkins_env_token_name aware of antivirus_api

- scripts/oneoff/categories-baseline.py
This adds a script requested by our performance analyst. It gives them data about which of our suppliers are resellers and which are selling original products. It also lists the categories each service has registered under. The script should be run against a local dump, as it hammers the API fairly hard. It outputs to TSV, because working with commas is hard and this was the path of least resistance.
[Ticket](https://trello.com/c/M5EBzmbK/398-export-g-cloud-service-data-for-benchmarking)
> Add basic script for generating categories/reseller report

- scripts/notify-suppliers-whether-application-made-for-framework.py
Trello: https://trello.com/c/doKzE2ED/409-jenkins-job-notify-suppliers-whether-application-made-for-framework-outputs-a-bunch-of-personal-data-thats-fun
Previously emails were being displayed in Jenkins log output 🙀 Now they are hashed. 
I've also rejigged the DRY_RUN log output to be more human readable. 
Before: 
```
INFO [Dry Run] Sending email de02a7e3-80f6-4391-818c-48326e1f4688 to u-k7kd56LcMCUW0Zne3-iqbhmwHGR0EBFmbTyPBAarA=
```
After:
```
INFO [Dry Run] Sending application_made email to u-k7kd56LcMCUW0Zne3-iqbhmwHGR0EBFmbTyPBAarA=
```
> Hash emails in 'application made' script output

- dmscripts/generate_supplier_user_csv.py
- tests/test_generate_supplier_user_csv.py
We had an issue where CSVs with no rows were being created legitimately (because there were no entries in the database that fit the criteria), but the CSV export script was failing to upload this to s3 as it thought this was due to an error.
This PR changes the `generate_csv_and_upload_to_s3` procedure so it only aborts if it does not have a valid s3 filename.
This does mean that in future it is possible for CSVs with only a header row to be uploaded.
> Fix csv export so only aborts if no data found

- requirements-app.txt
- requirements.txt
This will allow scripts to recognise email addresses separated by ampersands (see alphagov/digitalmarketplace-utils#515).
> Update digitalmarketplace-utils from 46.3.0 to 48.1.0

- scripts/oneoff/categories-baseline.py
- scripts/oneoff/export-service-categories.py
Trello: https://trello.com/c/Abra4gwN/454-export-g10-services-data-for-ash
Adds organisation size to export.
The files are generated separately by lot, so we shouldn't need to add that in.
Paired with @agalamatis 👍
> Adding organisationSize column to service export

- dmscripts/generate_supplier_user_csv.py
Previously generate_supplier/user_csv would return early if there was no
data from the server, effectively treating this as an error.
However it is very possible that there might be no data for whatever
reason; we should warn but then continue as normal.
> Change so that no suppliers/users is a warning only

- README.md
- dmscripts/generate_framework_master_csv.py
- dmscripts/helpers/framework_helpers.py
- dmscripts/helpers/supplier_data_helpers.py
- dmscripts/mark_definite_framework_results.py
- dmscripts/scan_g_cloud_services_for_bad_words.py
- requirements-app.txt
- requirements.txt
- scripts/export-framework-results-reasons.py
- scripts/generate-framework-master-csv.py
- scripts/mark-definite-framework-results.py
- scripts/oneoff/generate-fake-g-cloud-services.py
- scripts/oneoff/save-signed-agreement-path.py
- tests/helpers/test_supplier_data_helpers.py
https://trello.com/c/Px4kcY6B/462-exclude-fake-suppliers-from-framework-results-script
New optional keyword parameters to exclude fake suppliers for:
- generate-framework-master
- mark-definite-framework-results
- export-framework-results-reasons
PS: Also bumped the apiclient and explicitly calling `find_framework_suppliers` with `with_declarations=None` which used to be the default.
> Hide fake suppliers

- dmscripts/bulk_upload_documents.py
- dmscripts/helpers/file_helpers.py
- dmscripts/helpers/s3_helpers.py
- scripts/framework-applications/bulk-upload-documents.py
- scripts/generate-supplier-user-csv.py
- scripts/upload-counterpart-agreements.py
- tests/helpers/test_file_helpers.py
- tests/helpers/test_s3_helpers.py
- tests/test_bulk_upload_documents.py
No ticket - fix for broken export scripts.
- Moves `get_bucket_name` into a new helper module
- Adds `reports` to the list of approved bucket types
> Move get_bucket_name into helper module

- scripts/oneoff/swap-supplier-duns.py
Trello: https://trello.com/c/l5647BuW/733-duns-change-from-dave
Slightly tidied-up version of the script I've been using to swap DUNS numbers for two suppliers. It does the update in 3 steps, using a temporary dummy DUNS. It's verbose on purpose to make it clear what's happening at each step.
It performs some basic checks before attempting the swap:
- the suppliers should not already have the target DUNS numbers
- the existing DUNS numbers for the suppliers should match the target DUNS numbers (i.e. you can only set supplier 1's new DUNS to supplier 2's existing DUNS, and vice versa)
- the two target DUNS numbers should be different 
- the target DUNS numbers should be 9 digits
> Script to swap DUNS numbers for two suppliers

- dmscripts/helpers/auth_helpers.py
- dmscripts/send_stats_to_performance_platform.py
- scripts/framework-applications/send-stats-to-performance-platform.py
- scripts/send-stats-to-performance-platform.py
- tests/helpers/test_auth_helpers.py
- tests/test_send_stats_to_performance_platform.py
Trello: https://trello.com/c/TZoo1F5B/480-performance-platform-jenkins-job-leaks-token
The token is currently retrieved from credentials when the Jenkins job is generated from the template and output in the Jenkins console (and the config!!). 
Rather than stick yet another var into the main Jenkins config (in this case there would be one for each framework!) we can get the script to decrypt it from either the Jenkins environment (if it's there) or the credentials repo, like we do for the API tokens.
For example:
```
docker run -e DM_DATA_API_TOKEN_PREVIEW digitalmarketplace/scripts scripts/my-amazing-script.py preview --notify-api-key=ABC1234
```
Can become (with a small tweak to the script):
```
docker run -e DM_DATA_API_TOKEN_PREVIEW -e NOTIFY_API_KEY digitalmarketplace/scripts …
```
> Get tokens from creds for performance platform stats script

- dmscripts/notify_suppliers_of_brief_withdrawal.py
- tests/test_notify_suppliers_of_brief_withdrawal.py
To sort out https://trello.com/c/rNsjCmNh
This is a minimal fix allow support of splitting on multiple-address separators.
Going further to give this script better ergonomics I think we should consider combining it with `notify_suppliers_of_awarded_briefs.py` as elaborated on in https://trello.com/c/wDzrqj9n
> notify_suppliers_of_brief_withdrawal.py: use get_email_addresses from helpers to process emails

- scripts/framework-applications/generate-framework-master-csv.py
- scripts/framework-applications/mark-definite-framework-results.py
- scripts/framework-applications/notify-successful-suppliers-for-framework.py
- scripts/framework-applications/update-framework-results.py
I've checked through all these framework scripts (ready for G11) and moved them to the `framework-applications` folder.
There are a couple more framework scripts that I haven't moved yet, because they are linked to a Jenkins job (and therefore should probably go in a separate PR).
> Tidying framework application scripts

- dmscripts/export_framework_results_reasons.py
- dmscripts/helpers/csv_helpers.py
- scripts/framework-applications/export-framework-applicant-details.py
- scripts/framework-applications/generate-framework-master-csv.py
- tests/test_export_framework_results_reasons.py
Trello: https://trello.com/c/6YtiqGD0/522-framework-data-export-script-filenames-dont-match-the-runbook
Stressed-out devs have enough to do after closing a framework, without having to dig through the [runbook](https://docs.google.com/document/d/13wzZB2M16n4eVrn8zoaL90FkaYKksKJnUSCtUlIgPQE/edit) and rename the data export files to the format that CCS is expecting.
I've kept the datestamps (and added them to the pass/fail report) as they might still be useful.
> Align framework export filenames with CCS naming conventions

- schemas/digital-outcomes-and-specialists-4.declaration.json
Trello: https://trello.com/c/kTVN6PlQ/532-clone-dos4-content
The declaration schema is generated by a script in the frameworks repo (see https://alphagov.github.io/digitalmarketplace-manual/content-and-frameworks/adding-frameworks.html#generate-the-assessment-schemas).
~The service schemas are... not script-generated. I copied the DOS3 equivalent and added in the new top-level question for the `outcomes` lot, which meant splitting out the shared schema option for `outcomes` and `specialists`. However I think this may no longer be needed, provided we add in the correct validation to the API schemas (so that the supplier is forced to give the correct answer when creating the service during their application). Hence the WIP on this PR.~ Service validation now done in the API 🎉
> DOS4 assessment schemas

- scripts/framework-applications/publish-draft-services.py
I am stupid.
Nearly ended up giving all the live service document names an assets host of `https://dummy.endpoint`.
> publish-draft-services.py: fix default assets endpoint being applied universally

- dmscripts/helpers/supplier_data_helpers.py
- functional-tests/notify-successful-suppliers-for-framework/setup.sh
- functional-tests/notify-successful-suppliers-for-framework/suppliers.t
- functional-tests/notify-successful-suppliers-for-framework/usage.t
- scripts/framework-applications/notify-successful-suppliers-for-framework.py
I made a few changes based on what I would liked to have had when running this recently:
- Reorganise usage string
- Add dry-run flag
- Allow filtering supplier ids
- Add functional tests
- Hash email addresses in logs to prevent leaking PII
> Refactor notify-successful-suppliers-for-framework script

- Dockerfile
- functional-tests/validate-cloudtrail-logs/config-file.fixture
- functional-tests/validate-cloudtrail-logs/config-file.t
- functional-tests/validate-cloudtrail-logs/dates.t
- functional-tests/validate-cloudtrail-logs/output.t
- functional-tests/validate-cloudtrail-logs/setup.sh
- functional-tests/validate-cloudtrail-logs/usage.t
- scripts/validate-cloudtrail-logs.sh
Part of work to add a CloudTrail log validating job to Jenkins (ticket [here](https://trello.com/c/Ijzuk0qY/508-log-file-validation-job)). The script requires the CloudTrail ARNS to be added to the credentials repo alphagov/digitalmarketplace-credentials#221.
Rather than putting the script straight in a job I thought I would make separate PR for it here, so I can add tests and watnots.
> Add script for validating AWS CloudTrail logs

- dmscripts/export_framework_applicant_details.py
- dmscripts/generate_framework_agreement_signature_pages.py
- scripts/generate-framework-agreement-counterpart-signature-pages.py
https://trello.com/c/skEefuVb/893-regenerate-fwas-for-suppliers
Spoiler: I already used this script to regenerate the PDFs needed for the support request (see ticket).
We don't seem to use Country in the PDF at all so I left that out.
No tests yet - comments on the general approach v welcome.
The corresponding PR for the agreements repo: https://github.com/alphagov/digitalmarketplace-agreements/pull/6
> Use central supplier details for framework agreement PDFs

- scripts/oneoff/export-service-categories.py
https://trello.com/c/xho4skxE/889-ccs-request-for-g10-service-data-export
Agreed with Ash that adding these two fields (which are present in all lots) is fine for now. Adapting the script to include lot-specific fields is going to be too time-consuming.
> Include serviceFeatures and serviceBenefits in services export

- dmscripts/generate_supplier_user_csv.py
- tests/test_generate_supplier_user_csv.py
* Add field to csv export
* Add field to tests expecting this value
https://trello.com/c/schDS1vB/556-include-other-registration-number-in-official-supplier-details-csv
REQUIRES https://github.com/alphagov/digitalmarketplace-api/pull/945
> 556-include-other-registration-number-in-official-supplier-details-csv

- scripts/framework-applications/generate-successful-suppliers-for-framework-csv.py
The result of the script is no longer published publicly, but it's very useful when tallying stats of the framework just before it goes live. 
This also means we can include the Supplier ID which is a useful reference for any queries from CCS.
TODO: mention this script in the manual as a useful tool.
> Move script to framework-applications folder and include Supplier ID

- dmscripts/scan_g_cloud_services_for_bad_words.py
Very short term improvement for https://trello.com/c/5IGQchTX/
The number of terms we use is probably greater than the re module's cache size, causing continual `re` re-compiling. 
No tests! :balloon:  But appears to work.
> bad words script: hopefully make this a bit faster through reuse of compiled regexes

- scripts/api-clients-shell.py
- scripts/clients.py
- scripts/data-retention-remove-contact-information-data.py
- scripts/data-retention-remove-failed-suppliers-declarations.py
- scripts/data-retention-remove-supplier-declarations.py
- scripts/data-retention-remove-user-data.py
- scripts/export-dos-labs.py
- scripts/export-dos-outcomes.py
- scripts/export-dos-participants.py
- scripts/export-dos-specialists.py
- scripts/generate-framework-agreement-counterpart-signature-pages.py
- scripts/generate-supplier-user-csv.py
- scripts/get-model-data.py
- scripts/get-user.py
- scripts/index-to-search-service.py
- scripts/notify-buyers-to-award-closed-briefs.py
- scripts/notify-buyers-when-requirements-close.py
- scripts/notify-suppliers-of-awarded-briefs.py
- scripts/notify-suppliers-of-brief-withdrawal.py
- scripts/notify-suppliers-of-new-questions-answers.py
- scripts/notify-suppliers-whether-application-made-for-framework.py
- scripts/send-dos-opportunities-email.py
- scripts/snapshot-framework-stats.py
- scripts/update-index-alias.py
- scripts/upload-counterpart-agreements.py
- scripts/upload-dos-opportunities-email-list.py
- scripts/upload-file-to-s3.py
Our scripts are written against Python 3, we should make sure callers use Python 3.
> Explicitly call python3 in hashbang lines

- dmscripts/suspend_suppliers_without_agreements.py
- scripts/framework-applications/suspend-suppliers-without-agreements.py
- tests/test_suspend_suppliers_without_agreements.py
https://trello.com/c/naVLGC0L/599-mass-suspension-script
Script to bulk-suspend services for suppliers who have not returned their framework agreement. Admins can do this already for individual suppliers, but when there's 400+ suppliers to suspend, it can get tedious. 
~TODO: tests~ Tests now included!
~TODO: Make `--dry-run` do something~ `--dry-run` now does something 👍
> Script to bulk-suspend supplier services

- scripts/framework-applications/suspend-suppliers-without-agreements.py
https://trello.com/c/naVLGC0L/599-mass-suspension-script
Tested this on staging and realised the `w` was missing following a previous refactor.
> Reinsert missing write option on suspension script

- scripts/get-model-data.py
https://trello.com/c/WUPHdgSG/1007-export-data-failure-json-decode-error
One of the reports (brief-responses.csv) failed, stopping the entire script. This doesn't seem ideal.
This PR:
-  moves hardcoded lists of frameworks (that will soon need to be updated) to the top with the rest of the 'config'
- splits out the huge top-level script code into two functions
- adds a `try...except` around these functions to catch errors and continue on to the next 'config'
- updates the G-Cloud framework iterations we're exporting to slightly more interesting ones (G8 and G9 data is not changing any time soon!)
Out of scope for this PR:
- untangling the mess that is the testable functions for this script (i.e. moving my new functions into the testable modules and then testing them... maybe one day 😿 )
- …
> Improve get-model-data robustness

- scripts/api-clients-shell.py
Calling `IPython.embed()` in a function means the shell will be created in the scope of that function, which has a bunch of annoying side-effects, such as function definitions not being available in other closures.
The workaround seems to be to instead use `IPython.start_ipython()` and to do so in the global namespace (see [1]).
[1]: https://ipython.readthedocs.io/en/stable/interactive/reference.html#embedding-ipython
> Move embedded IPython shell into the global namespace

- scripts/framework-applications/update-framework-results.py
No ticket - just spotted this while setting a test account to 'failed' on DOS4.
The API token doesn't get passed as an argument to this script anymore, so let's take it out of the example.
> Fix update-framework-results script example

- dmscripts/export_dos_opportunities.py
- scripts/export-dos-opportunities.py
- scripts/get-model-data.py
- tests/test_export_dos_opportunities.py
https://trello.com/c/N3yUHHOe/92-make-dos-outcome-csv-framework-iteration-agnostic
- Splits out the public DOS opportunities CSV export from the mega `get-model-data` export (that exports a subset of model data to a private folder for internal use).
- Also adds tests & `--dry-run` functionality 🎉 
Currently, the Jenkins job doing the overnight export is also responsible for uploading this file to S3. This responsibility is now self contained within the script. (Updating the Jenkins job is next on my list - I won't merge this until that's ready).
This change should make the DOS opportunity export framework iteration agnostic - the file will be uploaded to the S3 bucket for latest live DOS framework. 
Having to fetch the brief responses for each brief via the API is a bit time consuming, …
> New DOS opportunities export script

- scripts/export-dos-opportunities.py
https://trello.com/c/N3yUHHOe/92-make-dos-outcome-csv-framework-iteration-agnostic
`digitalmarketplace` is all one word 😿
> Remove rogue hyphen from bucket name

- scripts/send-dos-opportunities-email.py
- scripts/upload-dos-opportunities-email-list.py
https://trello.com/c/uKsNvFiM/91-set-up-dos4-new-opportunities-supplier-mailing-lists-in-mailchimp
As per ticket:
These Mailchimp lists receive daily digests of the previous day's published DOS opportunities (depending on what lot the supplier is on) via `send-dos-opportunities-email.py`.
Once the lists are created and their IDs added to the right script (`upload-dos-opportunities-email-list.py`), users get automatically added to the list when Jenkins runs the script. This is normally done daily, to capture new users join an existing supplier account. 
We have separate lists for each DOS iteration, as suppliers on DOS3 but not DOS4 can't apply to DOS4 opportunities, so we don't want to spam them.
I have a separate branch-in-progress to refactor the `send-dos-opportunities` script to make …
> Add new DOS4 mailing list IDs

- dmscripts/send_dos_opportunities_email.py
- scripts/send-dos-opportunities-email.py
- tests/test_send_dos_opportunities_email.py
https://trello.com/c/58q6lRKF/33-update-dos4-regular-email-jobs
Basically a total rewrite of the DOS opportunities email script, that we send via Mailchimp. Previously the script took a `framework` arg, and could only be run for that framework. That meant that on the day after go-live, we'd have to manually run a catchup script to 'catch' the previous iteration's briefs that had been created before the switchover. 
The docstring has a thorough description of what's meant to be happening but the tl;dr is that the script should get all live briefs, sort them into framework/lot lists, and create/send the campaigns for each list. 
Comments very welcome. 
Changes to the equivalent Jenkins job: https://github.com/alphagov/digitalmarketplace-jenkins/pull/268
> DOS4 opportunity alerts run for all frameworks with live briefs

- dmscripts/helpers/html_helpers.py
This was identified as a risk by a recent IT health check. The change ensures that user input is escaped, preventing any nasties from applying XSS attacks.
[Ticket](https://trello.com/c/H2ubPYqz/306-enable-autoescape-on-jinja-templates)
> Enable autoescaping on html templates

- dmscripts/helpers/csv_helpers.py
- scripts/export-dos-labs.py
- scripts/export-dos-outcomes.py
- scripts/export-dos-participants.py
- scripts/export-dos-specialists.py
- tests/fixtures/content/frameworks/dos/manifests/edit_submission.yml
- tests/fixtures/content/frameworks/dos/questions/services/accessibleApplicationsOutcomes.yml
- tests/fixtures/content/frameworks/dos/questions/services/bespokeSystemInformation.yml
- tests/fixtures/content/frameworks/dos/questions/services/dataProtocols.yml
- tests/fixtures/content/frameworks/dos/questions/services/helpGovernmentImproveServices.yml
- tests/fixtures/content/frameworks/dos/questions/services/openStandardsPrinciples.yml
- tests/fixtures/content/frameworks/dos/questions/services/outcomesLocations.yml
- tests/helpers/test_csv_helpers.py
https://trello.com/c/bNJt7mYX/324-dos-lot-exports-are-not-in-the-right-format-and-have-extra-fields
Addresses some problems with the DOS export scripts:
- Fixes bug where `question.fields` was being called for question types that didn't have that attribute, and adds a couple of tests to check this (a `checkbox` type question previously worked fine, but a `boolean` type question would have failed)
- Adds DOS service fixtures to support the tests above. Mocking the content loader is a bit of a nightmare, so I thought we might as well use the real one, but feed it a tiny subset of our content to keep things speedy.
- Makes logging consistent across the four scripts
- Allows the user to specify an `output-dir` rather than hardcoding to 'output'
- Exports the actual expected filenames for each …
> DOS lot export scripts improvements

- scripts/oneoff/export-notify-templates-to-csv.py
https://trello.com/c/sHKgjXRC/1063-spike-manage-notify-template-and-reply-to-ids-outside-app-config
The goal of the ticket above was for us to manage our Notify templates better - having oversight of what templates we actually have seems like a quick win towards that goal! I rustled up this simple script to export the templates, and thought I might as well commit it.
The script includes an option to include the multi-line `body` field - if you're importing the CSV into a spreadsheet it makes it much harder to get an at-a-glance view of the templates, but it might be useful for content designers.
> Script to export Notify templates to CSV

- dmscripts/index_to_search_service.py
- tests/test_index_to_search_service.py
https://trello.com/c/d1jpHXSp
If https://github.com/alphagov/digitalmarketplace-api/pull/979 is merged this would allow the bulk of our briefs to be fetched in compressed responses, improving reliability.
> index_to_search_service: split iteration of briefs to index into two separate calls

- dmscripts/helpers/supplier_data_helpers.py
- scripts/framework-applications/notify-successful-suppliers-for-framework.py
https://trello.com/c/22mvlQsh/1061-log-supplier-id-during-notify-successful-suppliers-for-framework-script
This script takes a while to run, and it's hard to determine the progress as we only log the hashes of each emails we're sending.
Logging the supplier ID when building the personalisations for each user will help surface how far down the list of suppliers we've reached.
Also fixes a typo in an existing log statement.
> Log supplier ID during Notify successful suppliers for framework

- dmscripts/helpers/supplier_data_helpers.py
trello: https://trello.com/c/nmGTH8zd/111-1-notify-successful-suppliers-for-framework-script-doesnt-email-primary-contact
Tested on g-cloud and got 11937 instead of 10619 emails, I will keep the data sources and dumps for the reviewer(s).
> including the primary email in the success notification

- default.nix
- scripts/rotate-api-tokens.sh
- scripts/set-user-password-by-email-address.py
https://trello.com/c/AOxxcCSy
This was far more involved than I expected it to be, but doing it manually is annoying and error prone, so I wouldn't be beat.
`change-ft-account-passwords` will "detect" email/password combinations in a set of FT variables by looking for matching pairs of settings ending in `_email` and `_password`. It will then generate a new password for each account, separate accounts being determined by unique email address. A
github PR will then be created to apply these changes.
`sync-ft-account-passwords` will use the API to set the account passwords for any accounts found in a set of FT variables (detected in the same way).
Doing it this way allows separate accounts to be used for the different test variants, new classes of accounts could be added, or some accounts …
> rotate-api-tokens.sh: add new commands change-ft-account-passwords and sync-ft-account-passwords

- scripts/rotate-api-tokens.sh
Our frontends attempt to enforce a limit of 50 - let's not complicate things.
> ft account password rotation: limit passwords to 40 chars

- dmscripts/notify_suppliers_of_new_fw_cq_answers.py
- scripts/notify-suppliers-of-new-fw-cq-answers.py
- tests/test_notify_suppliers_of_new_fw_cq_answers.py
Originally https://trello.com/c/xbqxyfNV/ but has rather morphed into a separate script.
We can start off running this script when asked by CCS. It could be extended to run as a periodic job if this was found to be too much hassle, possibly detecting when to fire based on the etag of the most recent clarification question answers document found in the S3 bucket.
> add notify_suppliers_of_new_fw_cq_answers script

- dmscripts/notify_suppliers_of_new_fw_cq_answers.py
Stupid mistake - was simply causing logging output to be wrong.
> notify_suppliers_of_new_fw_cq_answers: fix inversion of run_is_new determination

- dmscripts/notify_suppliers_with_incomplete_applications.py
- scripts/notify-suppliers-with-incomplete-applications.py
- tests/test_notify_suppliers_with_incomplete_applications.py
https://trello.com/c/AzV9twDI/219-revise-1-week-reminder-email-to-prompt-applicants-with-any-incomplete-draft-services
For DOS4, some suppliers didn't realise they had incomplete services that needed to be submitted. This PR tweaks the reminder script to include a message with the number of incomplete services (unless the supplier hasn't submitted *any* services, in which case the original 'mark at least one of your services as complete' message is shown).
Other changes:
- the script now exits early if the framework is not `open` (the supplier can't make any changes if the framework is in any other state)
- the script is framework-agnostic (the Notify template was previously hardcoded to DOS4). This means formatting the application closing date using our special framework deadline date …
> Application reminder email includes incomplete service count

- dmscripts/export_framework_results_reasons.py
- tests/assessment_helpers.py
- tests/test_export_framework_results_reasons.py
To supplement https://github.com/alphagov/digitalmarketplace-frameworks/pull/603 and https://trello.com/c/kbTzccXb
We're adding extra constraints to the assessment schemas, constraints which in normal use we shouldn't expect to be broken. But if they are broken for some reason, we'll end up with a validation error that doesn't look as we expect it to, leading to problems when we try to run the "reasons" script.
This change just makes such errors less puzzling if they occur and adds a test for these cases.
>  export_framework_results_reasons: fail more obviously when we get unexpected validation errors

- dmscripts/export_framework_results_reasons.py
- dmscripts/helpers/framework_helpers.py
- tests/helpers/test_framework_helpers.py
- tests/test_export_framework_results_reasons.py
298-include-link-to-admin-view-in-failed-csv-report-we-send-to-ccs
https://trello.com/c/6ug1H0As/298-include-link-to-admin-view-in-failed-csv-report-we-send-to-ccs
Make 'frameworkSlug' available on record from client.get_supplier_framework_info response
Use record['frameworkSlug'] to create link to declaration in admin (with supplier id and stage hard coded to production)
* Add link to failed/ discresionary declaration in output csv for quick access by ccs
* Make frameworkSlug available in supplier info
* Update tests
> 298-include-link-to-admin-view-in-failed-csv-report-we-send-to-ccs

- scripts/snapshot-framework-stats.py
https://trello.com/c/AnvspHsL/1526-log-human-readable-stats-on-jenkins-framework-stats-output
Quick and dirty way to get a copy-and-pastable equivalent of the current framework application stats (see last year's performance platform https://www.gov.uk/performance/g-cloud-11-supplier-applications/applications-by-stage-tab/applications-by-stage-tab-applications-by-stage-day), as the current API JSON output is not the easiest to parse!
This way a developer can at least grab the latest Jenkins console output and easily share it with a Product Manager.
> Add human-readable log output to Jenkins console

- scripts/framework-applications/notify-suppliers-of-framework-application-event.py
docopt was interpreting one of our example lines as an option definition
and raising an error because of it.
> Fix notify-suppliers-of-framework-application-event script

- scripts/oneoff/gcloud-service-attribute-export.py
This script was written (and used) months ago but never committed - thought I'd stick it up for future reference.
A developer can easily slot in different service attributes depending on what they're after. The example below was used to fetch the free trial link URLs for a security audit, but I used a locally-amended version of it to see how many services contained Service Definition Document URLs as well.
> Service data export script

- scripts/framework-applications/snapshot-framework-stats.py
https://trello.com/c/huqe0wRJ/1550-whats-going-on-with-current-applications
The human-readable stats output service count is only including suppliers who've started (but not completed) a declaration, and submitted at least one service.
This fix includes any suppliers who haven't completed the declaration (i.e. including those who haven't even started it), but have submitted at least service.
> Include unstarted declarations in service count

- dmscripts/export_dos_opportunities.py
- scripts/export-dos-opportunities.py
- tests/test_export_dos_opportunities.py
https://trello.com/c/AuySMUcb/1559-add-more-logging-to-export-dos-opportunities-script
This job has been failing more than usual recently.
- Adds some logging so we can see the in-progress API calls
- Fixes a small bug when running the script locally (we aren't using the S3 helper function, so instead of uploading to the dev bucket, it attempts to upload to a non-existent bucket).
> Add logging for DOS opportunities export

- scripts/oneoff/add-licence-info-to-readme.sh
https://trello.com/c/Du4aEv02/468-update-readmes-for-our-repos
Our READMEs need some TLC - hardly any of them have Licence info, as recommended by the [GDS Way](https://gds-way.cloudapps.digital/manuals/readme-guidance.html#writing-readmes). There are a lot of repos, so I thought I'd write a script to get the Jenkins github user to do some of the heavy lifting for us.
The branch-creating and PR-creating functions are lifted from the token rotation script.
> One off script for appending licence info to READMEs

- .travis.yml
- requirements-dev.in
- requirements-dev.txt
- requirements.in
- requirements.txt
Now that pandas is gone (thanks to #491) the tests for Python 3.8 work :D
I also had to update some dm dependencies (thanks for flagging this up @domoscargin).
> Add tests for Python 3.7 and 3.8 to Travis CI

- dmscripts/get_user.py
- dmscripts/helpers/user_helpers.py
- scripts/get-user.py
As a team member testing the Digital Marketplace...
I want to be able to find a user with DOS opportunities in a certain state...
So that I can check different parts of the DOS journey.
This PR adds a command line flag `--brief-status=<status>` that tries to make it easier to do this. The UI is a bit unhelpful and you have to look at the api[[1]] to have an idea of what the different statuses mean, but it's a start?
[1]: https://github.com/alphagov/digitalmarketplace-api/blob/release-1029/app/models/main.py#L1543-L1591
> Add brief-status option to get-user script

- dmscripts/export_dos_opportunities.py
- tests/test_export_dos_opportunities.py
_bug discovered while investigating this card https://trello.com/c/0LD5lLbf/95-1-amend-opportunity-data-report_
The links in the DOS opportunity CSV previously did not resolve as they were missing `www.`
> fix brief URL in DOS opportunities CSV

- schemas/g-cloud-12-assessment-schema.json
Generated following the steps in the [developer manual](https://alphagov.github.io/digitalmarketplace-manual/content-and-frameworks/adding-frameworks.html#generate-the-assessment-schemas).
While working on https://trello.com/c/kCUjDnH4/48-3-3-jenkins-job-for-publish-services, I had to generate the G12 assessment schema to 'pass' my test suppliers. We might as well commit it now!
[Here's the PR committing the equivalent G11 schema](https://github.com/alphagov/digitalmarketplace-scripts/pull/380), for comparison.
> Add G12 declaration assessment schema

- dmscripts/export_dos_opportunities.py
- tests/test_export_dos_opportunities.py
https://trello.com/c/JDz7V5SO/1704-dos-opportunity-export-csv-missing-specialist-role
Previously this was looking for a field which was not returned by the API.
> fix specialist field in CSV

- scripts/framework-applications/notify-suppliers-of-framework-application-event.py
Spotted after the run failed midway through due to an unrelated Notify problem, and we couldn't resume it.
> Fix resume-run-id optional argument

- dmscripts/notify_suppliers_of_framework_application_event.py
- requirements-dev.txt
- requirements.in
- requirements.txt
- tests/test_notify_suppliers_of_framework_application_event.py
https://trello.com/c/EnPFfpum/1751-p3-incident-failure-to-send-g-cloud-12-clarification-questions-closing-email
- Pulls in new `dmutils.DMNotifyClient`, that now has the option to do a fresh lookup in the Notify API rather than using the client's sent references cache
- De-parametrizes the tests for `notify_suppliers_of_framework_application_event`, so we can better isolate the behaviour that's about to change
- Moves the tests into a class, so we can minimise the repetition from de-parametrizing 
- Finally, adds the kwarg `use_recent_cache` to the relevant notify client method calls, so we can use the fresh lookup if a `--resume-run-id` is provided.
There are 3 other scripts that require amending (see ticket), however they do not use `--resume-run-id` in the same way, so I'll address …
> Don't use DMNotifyClient's sent_references_cache when re-running failed script

- dmscripts/send_dos_opportunities_email.py
https://trello.com/c/Qk3SHoov/
We no longer need to track opens/clicks for individual users on the Mailchimp DOS Opportunities email campaigns (see ticket for details).
We will still be able to track anonymised clicks per campaign via analytics, using the `utm` suffix on the links.
> Turn off Mailchimp user tracking

- scripts/framework-applications/snapshot-framework-stats.py
https://trello.com/c/ahJ94DdS/202-1-performance-data-json-files-do-not-include-datetime-information﻿
> add date_generated key to snapshot framework stats json

- dmscripts/notify_suppliers_with_incomplete_applications.py
- scripts/notify-suppliers-with-incomplete-applications.py
- tests/test_notify_suppliers_with_incomplete_applications.py
https://trello.com/c/EnPFfpum
Part of the work to make our critical framework scripts more robust against Notify failures.
This script sends a reminder to suppliers with incomplete applications, 1 week before the deadline. It already logs the supplier ID if email sending fails. This PR adds functionality for a developer to re-run the script, passing a comma-separated list of supplier IDs to re-run against.
I've also refactored it a little:
- moved the initialisation of the `logger` and `DataAPIClient` instances to the top level script (to help this script be more consistent with our other scripts, and simplify the test setup). I tried moving the Notify client there as well but it was Unhappy. I may give this another go if people are keen but I was trying not to spend too much time on …
> Allow re-run of incomplete applications reminder via supplier ID list

- dmscripts/notify_suppliers_whether_application_made_for_framework.py
- scripts/notify-suppliers-whether-application-made-for-framework.py
- tests/test_notify_suppliers_whether_application_made_for_framework.py
https://trello.com/c/EnPFfpum/
This script already provides a facility for re-running with a list of supplier IDs from a previous failed run. However there were no tests for it 🙀 
I've added some! This meant moving some of the code to a separate module (consistent structure with our other scripts).
> Add tests for Notify suppliers whether application made script

- dmscripts/export_framework_applicant_details.py
- scripts/framework-applications/export-framework-applicant-details.py
- tests/test_export_framework_applicant_details.py
Tidies up an outdated docstring - we made this script framework agnostic for DOS4 last year.
Also moves the `logger` config to the top level script, for consistency with our other scripts.
> Tidy Export framework applicant details script

- requirements.in
- requirements.txt
Snyk notified us about a vulnerability in rsa<=4.1, https://app.snyk.io/vuln/SNYK-PYTHON-RSA-570831
This commit updates rsa to the latest version. We also need to loosen
the requirement on awscli to allow this.
> Bump rsa from 3.4.2 to 4.5

- scripts/oneoff/export-draft-services-for-suppliers.py
(No ticket - this is an old throwaway script I had on my machine, that I've tidied up so others might find useful in future.)
Sometimes we want to investigate all the draft services for a particular supplier (or list of suppliers), and any missing fields might have. This script uses a combination of `find_draft_services_by_framework_iter` and `get_draft_service` to find this information and export it to a handy CSV.
> One-off script for exporting draft services for a given list of suppliers

- dmscripts/export_framework_results_reasons.py
- tests/test_export_framework_results_reasons.py
The post-application CSV reports we generate for CCS had a typo: we were missing the `/admin` from the URLs where Sourcing admins can view declaration data.
> Fix path to admin declaration view

- dmscripts/mark_definite_framework_results.py
- scripts/framework-applications/mark-definite-framework-results.py
- tests/assessment_helpers.py
- tests/test_export_framework_results_reasons.py
- tests/test_mark_definite_framework_results.py
Final bit of post-G12 script cleanup. 
The `mark-definite-framework-results` script is used to automatically determine whether a supplier has passed or failed their declaration (given a JSON schema), and set the `onFramework` value in the API.
At one point, the script used to also validate service data (for DOS frameworks only - a service could have status 'failed'), however since DOS4 this validation has been done in the Supplier FE instead. This means a lot of redundant code and confusing instructions can now be removed from this script 🎉 
- Removes mentions of draft service schemas from top-level script docstring
- Remove code that assesses draft services using a schema
- Simplify the 'assess drafts' step (we still need to check that a supplier has at least 1 submitted draft)
- Test …
> Remove service validation from mark-definite-framework-results script

- scripts/oneoff/update_draft_service_via_csv.py
- scripts/oneoff/upload_draft_service_pdfs.py
- tests/test_update_draft_service_via_csv.py
- tests/test_upload_draft_service_pdfs.py
This PR contains two experimental scripts that could provide an alternative way for users to submit G-Cloud services, for example if accessibility problems prevented them from using the usual submission journey.
1. Update existing draft services from a folder of CSV files
The CSV files require a specific naming structure: `<supplier_id>-<lot-slug>-<service-name>.csv`. Lot is required in order to retrieve the correct questions for the service.
The CSV file content also needs to match the format exported by [scripts/framework-applications/generate-questions-csv.py](https://github.com/alphagov/digitalmarketplace-scripts/blob/master/scripts/framework-applications/generate-questions-csv.py). The script also currently hardcodes the number of question columns per lot.
Some service questions will …
> [Experimental] Alternative method for updating draft services and documents

- dmscripts/scan_g_cloud_services_for_bad_words.py
- tests/test_scan_g_cloud_services_for_bad_words.py
https://trello.com/c/ptvcsR37/321-scan-g-cloud-services-for-bad-words-via-jenkins
We don't want to bother scanning draft services with status `not-submitted`.
Also uses the `iter` methods to ensure we get all services for a supplier (eg if they have more than 100).
This script didn't have any tests (!) I've added a basic one for the main function - we can always add more later.
> Scan only submitted draft services for bad words

- scripts/oneoff/update_draft_service_via_csv.py
- scripts/oneoff/upload_draft_service_pdfs.py
- tests/test_update_draft_service_via_csv.py
- tests/test_upload_draft_service_pdfs.py
Following on from https://github.com/alphagov/digitalmarketplace-scripts/pull/527, adjust the `update_draft_service_via_csv.py` script to allow new services to be created, given an optional flag `--create-draft`.
If this flag is present, the script will not attempt to look up an existing service to update, but create a new draft with the service name given in the filename. The script then parses the JSON and updates the service as before. 
I also did a small bit of tidying for the `output_service_categories_features_and_benefits_summary` function. This now only outputs the items that caused a problem.
This PR also adds support for ODF formats in `upload_draft_service_pdfs.py` (I decided not to change the script name for now, to avoid confusion!) The default mode is still `pdf`, but other …
> [Experimental] Create draft services via CSV

- dmscripts/helpers/logging_helpers.py
- dmscripts/helpers/supplier_data_helpers.py
- scripts/framework-applications/notify-successful-suppliers-for-framework.py
We ran this earlier today, and noticed some possible improvements.
Fix the doc comment to include all the parameters and recommend providing the list of suppliers.
Also add in logs to the parts that take a while to give the person running the script an indication of progress.
I've manually tested that this gives the expected output when we run the script (with `--dry-run`, of course)
> Make the script to notify successful suppliers easier to understand

- requirements-dev.txt
- requirements.in
- requirements.txt
Will allow us to make use of https://github.com/alphagov/digitalmarketplace-apiclient/pull/234/, and other recent changes.
> Take updated dependencies

- scripts/api-clients-shell.py
Having direct access to production faintly terrifies me. Sometimes I just need to get information from prod. In those cases, it'd be useful to have protection against accidentally making changes.
Override `__getattr__` for access control. Override `__dir__` so that autocomplete in the iPython shell works.
I've done this on the assumption that API methods that start with "get_" or "find_" are read-only methods.
> Allow read-only access to the API client shell

- dmscripts/export_framework_applicant_details.py
- dmscripts/generate_framework_agreement_signature_pages.py
- dmscripts/helpers/framework_helpers.py
- requirements.in
- requirements.txt
- scripts/generate-framework-agreement-counterpart-signature-pages.py
- tests/assessment_helpers.py
- tests/helpers/test_framework_helpers.py
- tests/test_export_framework_applicant_details.py
https://trello.com/c/UfmJ2EOd/308-adapt-countersigning-jenkins-job-for-e-signature-flow
This makes a number of changes to the script to support e-signature counterpart documents
* Script is responsible for automatically approving the agreement using the API (This would have been done previously in admin-frontend)
* Adapt script to handle multiple documents to facilitate generation of a complete contract PDF
Co-authored-by: Laurence de Bruxelles <laurence.debruxelles@digital.cabinet-office.gov.uk>
Note, this is dependent on sister PR https://github.com/alphagov/digitalmarketplace-agreements/pull/10
> Adapt countersigning job for e-signatures

- dmscripts/export_framework_applicant_details.py
- dmscripts/helpers/framework_helpers.py
- scripts/generate-framework-agreement-counterpart-signature-pages.py
- tests/helpers/test_framework_helpers.py
In the case where a supplier had not signed the agreement and was on an e-signature framework we were erroneously looking up their agreement which would then 404 and cause an exception on the API client. This filters out suppliers without an agreement ID so that subsequent steps are not run for thm.
Co-authored-by: Laurence de Bruxelles <laurence.debruxelles@digital.cabinet-office.gov.uk>
> filter out e-signature suppliers without an agreementID

- dmscripts/generate_framework_agreement_signature_pages.py
This flag is required in 0.12.6 of `wkhtmltopdf` to enable access to external resources (linked static files) For more context see: https://stackoverflow.com/questions/62315246/wkhtmltopdf-0-12-6-warning-blocked-access-to-file/62315247#62315247
> add enable local file access flag

- dmscripts/helpers/framework_helpers.py
- scripts/framework-applications/suspend-suppliers-without-agreements.py
In previous framework iterations CCS have provided a list of suppliers to suspend; for G-Cloud 12 we want to suspend all suppliers who haven't returned a framework agreement.
This PR adds a helper `get_suppliers_without_agreements` and uses it in the bulk suspend script.
> Add helper to find suppliers without framework agreements for suspend script

- dmscripts/upload_counterpart_agreements.py
Reduce the risk of accidental PII leaks if we dry-run in Jenkins.
> Stop printing user emails when dry running

- scripts/oneoff/acknowledge_publish_draft_service_updates.py
We changed the user in the publish draft services script in https://github.com/alphagov/digitalmarketplace-scripts/pull/371, we need to reflect that change in this script too.
> Update acknowledge publish draft services audit user

- dmscripts/helpers/supplier_data_helpers.py
- scripts/generate-framework-agreement-counterpart-signature-pages.py
- tests/helpers/test_supplier_data_helpers.py
Minor followup to https://github.com/alphagov/digitalmarketplace-scripts/pull/562
I noticed from the Jenkins logs we are needlessly duplicate logging when there are no services to suspend e.g.
```
2020-10-03 03:16:53,431 script INFO Supplier 705880 has no disabled services on the framework.
2020-10-03 03:16:53,536 script INFO Setting 0 services to 'published' for supplier 705880.
2020-10-03 03:19:43,451 script INFO countersigning agreement 36250 for supplier 707725
```
> only log message if service ids

- scripts/framework-applications/snapshot-framework-stats.py
I noticed that when this script runs we get unformatted log messages such as
INFO:dmapiclient.base:API {api_method} request on {api_url} finished in {api_time}
See https://ci.marketplace.team/view/Framework%20lifecycle%20jobs/job/hourly-stats-snapshot-digital-outcomes-and-specialists-5-production/27/console for an example of this.
I think this is because we are using the `logging` module directly rather than the dmscripts logging configuration. This commit changes the script to use `dmscripts.helpers.logging.configure_logger`.
> Fix logging for framework application stats snapshot script

- scripts/oneoff/remove-dos4-questions-from-dos5-drafts.py
Script to update services from this ticket
https://trello.com/c/lNqAe34j/68-fix-dos-5-draft-services-with-improperly-copied-dos-4-answers
Some questions were removed from DOS5 but not flagged to not be copied from a DOS4 service. Affected draft services would always fail validation because they had answers to questions which don't exist.
This script finds affected draft services and deletes the answers to the removed questions.
> Remove DOS4 questions from DOS5 drafts

- dmscripts/helpers/updated_by_helpers.py
- requirements.in
- requirements.txt
- scripts/api-clients-shell.py
- tests/helpers/test_updated_by_helpers.py
Trello: https://trello.com/c/rACMNlvs/13-can-we-automatically-fill-in-your-email-when-using-the-api-client
Most of the API calls that modify state take a `user` or `updated_by` parameter for audit purposes. Filling in one's email can get rather tedious when using the API client shell.
Create a helper to work out who the user is using some heuristics. Use this to provide the `user` for the API client shell. Should save us a bit of typing and tedium.
Makes use of https://github.com/alphagov/digitalmarketplace-apiclient/pull/235/.
> Fill in user for API client shell

- scripts/oneoff/remove-test-service.py
Trello: https://trello.com/c/FGzgpSfC/1980-is-this-a-bug
The service has no declaration, so some links are broken.
> Remove broken test production supplier service

- dmscripts/helpers/logging_helpers.py
Add the timezone identifier to timestamps when logging from scripts. This will make it easier to consolidate logs across multiple events or scripts.
Closes ticket https://trello.com/c/wRGIKhhf/1091-05-add-timezone-identifier-to-timestamps-in-logging-format-of-scripts
> Add timezone to timestamp logging format

- scripts/oneoff/remove-dos4-questions-from-dos5-drafts.py
Trello: https://trello.com/c/n5p5CgRz/1983-ccsrequests-re-problem-with-dos5-application-on-digital-marketplace
`find_draft_services_by_framework` produces paged output, so we were missing lots of affected draft services. Instead use the `iter` variant which allows us to search all drafts.
This should let us fix the 122 affected drafts we'd previously missed.
> Get all drafts before filtering

- scripts/scan-pdf-content.py
Add a script that scans supplier uploaded PDFs stored in S3 for JS or other unusual content types.
Part of ticket https://trello.com/c/SIYebkbk/237-3-scan-service-docs-and-produce-list-of-services-with-non-conforming-pdfs
> Add script to scan supplier PDFs for JS content

- scripts/scan-pdf-content.py
Replace the `--index` optional argument with `--resume` which calculates the index to resume from the number of rows in the report CSV. 
Part of https://trello.com/c/SIYebkbk/237-3-scan-service-docs-and-produce-list-of-services-with-non-conforming-pdfs
> Add --resume to PDF scan script

- scripts/oneoff/export-approved-service-edits.py
Ticket: https://trello.com/c/Yg0KjHkw/2050-ccsrequests-service-edits-report
For reporting purposes CCS need to see how many service edits are approved in a month. This information is not currently available in the admin frontend, so this commit adds a script that exports the relevant information to a CSV.
> Add script to export approved service edits

- dmscripts/notify_buyers_to_award_closed_briefs.py
- dmscripts/notify_buyers_when_requirements_close.py
- dmscripts/notify_suppliers_of_awarded_briefs.py
- dmscripts/notify_suppliers_of_framework_application_event.py
- dmscripts/notify_suppliers_of_new_questions_answers.py
- dmscripts/notify_suppliers_whether_application_made_for_framework.py
- dmscripts/notify_suppliers_with_incomplete_applications.py
- dmscripts/upload_counterpart_agreements.py
- requirements.in
- requirements.txt
- scripts/framework-applications/notify-successful-suppliers-for-framework.py
- tests/test_notify_buyers_to_award_closed_briefs.py
- tests/test_notify_buyers_when_requirements_close.py
- tests/test_notify_suppliers_of_awarded_briefs.py
- tests/test_notify_suppliers_of_framework_application_event.py
- tests/test_notify_suppliers_of_new_questions_answers.py
- tests/test_notify_suppliers_whether_application_made_for_framework.py
- tests/test_upload_counterpart_agreements.py
For Notify batch scripts an issue with a template such as a missing personalisation will cause all emails that would be sent by the script to fail. In this situation the script should fail fast, rather than try and continue and waste cycles.
This also reduces the possibility of https://trello.com/c/kwVKRjEm/1460-jenkins-job-notify-suppliers-of-framework-application-event-production-keeps-running-even-after-being-aborted happening again, because the script should hopefully stop itself instead of having to be killed.
> Change notify scripts to fail fast if there is a template error

- schemas/digital-outcomes-and-specialists-5.declaration.json
The validation schema is needed for Jenkins to determine automatic passes or failures when checking suppliers applications to DOS5.
https://alphagov.github.io/digitalmarketplace-manual/content-and-frameworks/framework-lifecycle-for-developers.html#pending
Schema generated from https://github.com/alphagov/digitalmarketplace-frameworks/blob/master/scripts/generate-assessment-schema.py 
https://trello.com/c/8tkVDOur/554-05-run-declaration-assessment-script
> Add DOS5 validation schema

- dmscripts/export_service_edits.py
- dmscripts/helpers/datetime_helpers.py
- scripts/oneoff/export-approved-service-edits.py
- scripts/oneoff/export-service-edits.py
Occasionally we get asked to provide details about historical changes to a service. This script should make answering those requests a little easier.
> Add script to export details about service edits

- dmscripts/helpers/logging_helpers.py
We [hoped](https://github.com/alphagov/digitalmarketplace-scripts/pull/570) it would give us the ~microseconds~ milliseconds, but it didn't.
> Remove ',uuu' from logs

- dmscripts/export_dos_opportunities.py
- scripts/export-dos-opportunities.py
- tests/test_export_dos_opportunities.py
Ticket: https://trello.com/c/s5IrVY70/2122-ccsrequest-queries-relating-to-the-digital-marketplace-for-dos-team
Currently CSS admins have to cross-reference buyer user details with an opportunity by hand, which is time-consuming for them.
This commit expands the export-dos-opportunities script to generate an additional CSV with extra details about the buyer user. As we don't want to make this information publicly available, this new CSV is uploaded to the reports bucket with private permissions; a change to the admin frontend will be needed to allow admins to download this file.
> Add admin-only CSV with buyer user details to DOS opportunities export script

- dmscripts/export_dos_opportunities.py
- tests/test_export_dos_opportunities.py
* Log messages now show the key for the uploaded file
* Admin-only CSV has the correct permissions to allow download via signed url
There is more detail in the commit message.
> Fix bugs in export-dos-opportunities script

- requirements-dev.in
- requirements-dev.txt
- requirements.txt
- tests/conftest.py
We want to install digitalmarketplace-test-utils from PyPI instead of VCS, so we can rely on Dependabot to update our apps automatically when a new version is available.
> Bump digitalmarketplace-test-utils from git to PyPI

- scripts/framework-applications/remind-suppliers-to-sign-framework-agreement.py
Previously this email was sent by `notify-successful-suppliers-for-framework.py` and passing the reminder email template rather than the first 'please e-sign' email. This meant that all suppliers got a reminder email - even if they'd already signed the agreement.
By separating the reminder email into its own script we can only email the suppliers who have not yet signed.
https://trello.com/c/o3VqNKUQ/688-1-only-send-reminder-email-43-to-suppliers-who-have-not-signed
[Reminder email template](https://www.notifications.service.gov.uk/services/95316ff0-e555-462d-a6e7-95d26fbfd091/templates/b4c60768-abb8-4fb3-b1f1-09259df7ee11)
[Email sent to the test suppliers on preview](https://www.notifications.service.gov.uk/services/95316ff0-e555-462d-a6e7-95d26fbfd091/notification/29abd6e5-c79e-466d-8a7 …
> Add script to send e-signature reminder email

- scripts/framework-applications/remind-suppliers-to-sign-framework-agreement.py
Switch to `find_users_iter` just in case there are any suppliers who have more users than the regular `find_users` method will return. Thanks to @bjgill for spotting the edge case!
https://trello.com/c/o3VqNKUQ/688-1-only-send-reminder-email-43-to-suppliers-who-have-not-signed
> Handle suppliers who have many users in reminder email script

- scripts/framework-applications/suspend-suppliers-without-agreements.py
Previously this script suspended suppliers who have not signed the framework agreement and exported a CSV of email addresses to notify.
These email addresses were then uploaded to Notify and a reminder email was sent manually.
In the interests of saving time, reducing the scope for errors and not having personal data on our laptops, modify the script so it also sends the emails.
I have checked to make sure this script isn't used by any Jenkins jobs.
https://trello.com/c/ieH4CTed/699-1-make-script-to-suspend-suppliers-who-havent-signed-also-send-the-email
[Notify email template](https://www.notifications.service.gov.uk/services/95316ff0-e555-462d-a6e7-95d26fbfd091/templates/f4224b66-42cc-45c3-b55a-2cf5cb95792f)
Email sent:
> Change script that suspends suppliers to also send a reminder email

- scripts/oneoff/delete_trello_pii.py
- scripts/oneoff/get_trello_attachments.py
Trello: https://trello.com/c/tq75g1XZ/2148-what-do-we-do-about-historic-lists-of-user-emails-stored-in-trello
Some of our CSV attachments in Trello contain user data (emails, mostly). We want to find and delete all such attachments.
Create a script to get us all our Trello cards with CSV attachments. This needs to be run by someone with access to all our Trello teams/boards. They'll need to get a Trello API key and token and provide them as environment variables.
Create a second script that reads the list of attachments and presents them for a human to determine whether they contain PII. If the human says yes, the script deletes the attachment.
Note - this is all quite rough and of generally poor quality. However, we're only going to run this once, so I think that's OK
> Scripts to identify and delete Trello CSV attachments containing PII

- scripts/framework-applications/remind-suppliers-to-sign-framework-agreement.py
Previously the script filtered for all suppliers who had an interest in a framework and who hadn't signed their framework agreement. This includes the users we wanted to email, but mistakenly also sent emails to supplier users who had started an application but not completed it, or those who were unsuccessful in their application.
We want to email just the suppliers who have made a successful application and not yet signed their agreement. This script is run towards the end of standstill so by that point we'll have run the script to mark automatic successes, CCS will have made decisions on all discretionary applications and therefore all suppliers who have successfully applied will have `onFramework` set to `True` in the database.
To get to the users we want we can get all the suppliers …
> Fix to filter to only suppliers who have made a successful application

- dmscripts/helpers/auth_helpers.py
- dmscripts/helpers/supplier_data_helpers.py
- scripts/framework-applications/remind-suppliers-to-sign-framework-agreement.py
- scripts/oneoff/open_g12_recovery_for_suppliers.py
Trello: https://trello.com/c/0g9FxjRJ/680-1-as-a-developer-i-can-run-a-script-to-let-all-recovery-users-know-the-recovery-process-is-open
We have drafted an email we're going to send to users when the G12 recovery process opens. The email will tell the users what they need to do. This script will be used to send that email.
Add some helpers to make this a bit easier. 
The Notify template is: https://www.notifications.service.gov.uk/services/95316ff0-e555-462d-a6e7-95d26fbfd091/templates/347e1ed7-ec83-45a0-bb16-832f244f8919. Note that we're currently missing the closing date. There's a story that tracks getting that filled in once we know the dates.
> Inform users when the G12 recovery process opens 

- scripts/framework-applications/notify-suppliers-with-signed-framework-agreement.py
Ticket: https://trello.com/c/KZN6ESr7/713-1-send-dos5-comms-that-framework-is-live
We want to be able to send an email to all suppliers who have signed their framework agreement when a framework goes live. This commit adds a script that sends a given Notify email template to all suppliers with a signed framework agreement.
It was almost entirely copied from `scripts/framework-applications/remind-suppliers-to-sign-framework-agreement.py`, and then modified to have the personalisations needed for Notify template "50b Services are live (DOS 5)" (98a9754d-9310-436a-9e7a-cc7504ecd92d).
I will try and add tests before we need to use it, but reviewers are encouraged to try it out with `--dry-run` :sweat_smile:.
> Add notify-suppliers-with-signed-framework-agreement.py

- scripts/oneoff/get_g12_recovery_services.py
- scripts/oneoff/handle_missing_g12_recovery_services.py
- scripts/oneoff/handle_too_many_g12_recovery_services.py
Trello: https://trello.com/c/13Ryt5o5
As part of the G12 recovery, we need a list of the IDs of the recovery drafts. This will allow us to hide irrelevant drafts to avoid confusion.
We have a CSV containing the un-normalised service names. For each, get all drafts for that supplier that have a matching service name when normalised. Output the same CSV with the new data in a new column.
Then create new empty drafts for any missing drafts. This depends on https://github.com/alphagov/digitalmarketplace-api/pull/1083
Some services have multiple drafts, which is not what we want. So choose the draft with the most completed answers.
My plan is to merge this, run the scripts, and then update the G12 recovery spreadsheet with the results.
> Get one draft ID for each G12 recovery service

- .github/workflows/test.yml
Since `lxml` upgrade in #604 we no longer need additional ubuntu dependencies to build against python 3.9.
> remove unneeded ubuntu dependencies

- Dockerfile
- requirements-dev.txt
- requirements.in
- requirements.txt
Currently we have awscli in our requirements files with other Python packages, however this makes upgrading very hard because awscli always requires a specific version of botocore, and this causes lots of depenendency conflicts with boto3. To get around this we instead install awscli into it's own venv with it's own version of botocore using [pipx].
[pipx]: https://pipxproject.github.io/pipx/
> Install awscli in seperate virtual environment to other Python packages

- scripts/oneoff/export-framework-search-filters.py
Ticket: https://trello.com/c/XAgEQjUw/2171-export-list-of-g-cloud-12-filters-and-categories
CCS want to be able to see the current search filters and categories for G12 so they can make improvements for G13. This commit adds a script to collate the information from the frameworks repo into one spreadsheet.
Note to reviewers: a lot of the code is copied from the buyer frontend with minimal changes so it's easier to tell if the buyer frontend diverges in future.
> Add oneoff script export-framework-search-filters

- dmscripts/helpers/auth_helpers.py
- scripts/oneoff/get-g12-recovery-draft-status-csv.py
We have set up G12 recovery to close automatically based on the date and time (see https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1347) so the list of draft IDs will still be in credentials after it's closed.
https://trello.com/c/ounXbBp3/718-1-give-ccs-what-they-need-to-decide-which-submitted-draft-services-should-be-on-the-framework
> Add script to export G12 recovery draft data to CSV

- scripts/oneoff/get-jenkins-functional-test-build-data.py
As part of our work to improve our automated tests we want to know how long our functional tests take to run and the proportion of runs that fail.
Jenkins stores this information for past builds for 60 days or until there are 100 builds in the history per job, and makes it available through the REST API. Fetch all available history  for the Preview and Staging functional test jobs and write to a CSV.
https://trello.com/c/oeYMogTp/807-3-measure-functional-test-average-speed-to-provide-baseline
> Add script to export functional test build data from Jenkins

- scripts/oneoff/notify-g12-suppliers-with-no-submitted-services.py
Borrowed heavily from https://github.com/alphagov/digitalmarketplace-scripts/compare/bg-close-g12
[Notify template](https://www.notifications.service.gov.uk/services/95316ff0-e555-462d-a6e7-95d26fbfd091/templates/7ff14f15-b869-49b1-b2cc-a576fb054a45)
If this script was going to stay around for longer than a few days it should probably be combined with the other email script that notifies suppliers who **did** submit at least one draft service. It's not so I think having two scripts to send the emails is fine.
https://trello.com/c/DteCbA85/828-1-as-a-supplier-i-get-an-email-telling-me-submitted-no-draft-services
> Add script to email G12 suppliers who didn't submit any services

- scripts/oneoff/send_g12_recovery_reminder_for_suppliers.py
Trello: https://trello.com/c/M8EeBspq
We're going to send a reminder to the suppliers involved in the recovery. It closes tomorrow at 2pm, and many suppliers have not yet marked their services as complete. Create a script to send this email, copying from open_g12_recovery_for_suppliers.py, which was very similar.
Uses the Notify template (https://www.notifications.service.gov.uk/services/95316ff0-e555-462d-a6e7-95d26fbfd091/templates/6cc94b27-e4d7-49e3-b100-8ac349c97d04). Copied from Nora's agreed draft.
Subject: "Reminder: complete your G-Cloud 12 services by 2pm on 25 February 2021"
> Add script for G12 recovery reminder

- scripts/oneoff/notify-g12-suppliers-with-submitted-services.py
Borrowed heavily from #637.
[Notify template](https://www.notifications.service.gov.uk/services/95316ff0-e555-462d-a6e7-95d26fbfd091/templates/d8907d3f-164a-4929-bbe6-5d174f04ac2f)
I had to add a new variable to the template to allow for the logic to send the framework agreement message to the one supplier who has not yet signed. I also modified it so we say `1 service` and `2 services`.
https://trello.com/c/0YicABRj/793-2-as-a-supplier-i-get-an-email-telling-me-how-many-draft-services-i-submitted
Email to most suppliers:
Email to the supplier who hasn't signed:
> Add script to email G12 suppliers who submitted at least one service

- scripts/oneoff/mark-g12-supplier-status.py
We have one supplier in the G12 recovery process who has not yet signed the framework agreement. In order for them to be able to do this, we need to evaluate their answers to the declaration questions and mark them as being on G-Cloud 12 if they pass.
This script borrows heavily from `digitalmarketplace-scripts/blob/master/scripts/framework-applications/mark-definite-framework-results.py` to do so for this single supplier.
Note: Their declaration *looks* fine from a quick manual comparison against the schema. Therefore I've not written code to export their declaration answers if they don't pass automatically. If that's needed, we'll probably want to borrow from
`scripts/framework-applications/export-framework-results-reasons.py`
https://trello.com/c/QwO6dH3A/794-1-make-sure-recovery-suppli …
> Add script to evaluate G12 recovery supplier declaration

- dmscripts/notify_suppliers_of_awarded_briefs.py
I think the previous behaviour was probably wrong. We do officially support multiple email addresses in this field - the hint text is "You can add more than one email address. Use a comma between each email address."
Users sometimes enter things that aren't emails - for instance names or URLs. This happens quite commonly - I've seen [4 such awarded brief responses in the past month](https://ci.marketplace.team/job/notify-suppliers-of-awarded-briefs-production/).
In no cases have we taken any action as a result of only some of the email addresses being invalid. So I don't think it's useful to fail the script in this case. Instead, downgrade to a warning. We will still error if there is no valid email address.
I've raised a story to improve our input validation: …
> Only error if all emails invalid

- dmscripts/publish_draft_services.py
It needs to be escaped, otherwise CustomLogFormatter tries to double-format it. This is harmless, but it does produce an extra log message: https://github.com/alphagov/digitalmarketplace-utils/commit/d4a0591962d613cdb7f1a3c7fe995bb4f9bab233
Escape the dictionary to reduce the log spam.
> Escape dictionary for logging

- scripts/oneoff/copy-uncopied-service-documents.py
https://govuk.zendesk.com/agent/tickets/4533790
During the G12 recovery, we published 17 services without copying their service documents to the documents bucket. So the document links did not work.
Find the affected documents, copy them to the correct bucket, and update the affected services with the new URL.
I've done a dry-run of this, and it looked as if it should do the right thing.
Copies extensively from `scripts/framework-applications/publish-draft-services.py`.
> Copy uncopied G12 service documents

- dmscripts/email_engine/__init__.py
- dmscripts/email_engine/cli.py
- dmscripts/email_engine/logger.py
- dmscripts/email_engine/queue.py
- dmscripts/email_engine/typing.py
- dmscripts/notify_suppliers_of_awarded_briefs.py
- scripts/notify-suppliers-of-awarded-briefs.py
- tests/email_engine/conftest.py
- tests/email_engine/test_cli.py
- tests/email_engine/test_email_engine.py
- tests/email_engine/test_queue.py
- tests/email_engine/test_typing.py
- tests/test_notify_suppliers_of_awarded_briefs.py
Adds a framework for writing scripts that send emails that aims to be
- Reliable
- Repeatable
- Auditable
The theory is based around a suggestion from @alex9smith and @bjgill, when running the email engine logs email notifications that are outstanding and sent are recorded in a human readable log file. If the script fails partway through sending emails, it can read back its own log file to pick up where it left off.
To use the email engine, the script provides a [generator function](https://wiki.python.org/moin/Generators) that calls the Digital Marketplace API and yields notifications to be sent; `dmscripts.email_engine.email_engine` handles everything else, including resuming failed runs, logging, and command line argument handling:
```python
from dmapiclient import DataAPIClient
from …
```
> Add email engine framework for writing scripts that send emails

- dmscripts/email_engine/__init__.py
- dmscripts/email_engine/cli.py
- tests/email_engine/test_cli.py
- tests/email_engine/test_email_engine.py
https://trello.com/c/3hLue99t/919-1-finish-creating-a-system-for-bulk-email-scripts-that-is-reliable-repeatable-and-auditable
In order to make it easier to retry jobs when run on CI, only include the argument hash when no reference is specified.
This supports the changes in https://github.com/alphagov/digitalmarketplace-jenkins/pull/422/commits/c6eda3be1a958cc1cfe9ef9b299f463dce3976ab to allow re-running of jobs on Jenkins.
> only include hash in reference where no reference specified in args

- scripts/oneoff/redact_brief_response.sql
A brief response has data that we need to redact - see https://govuk.zendesk.com/agent/tickets/4540337. To ensure the data is completely removed, we also need to redact all related audit events.
There is no way to do this via the API. We don't want to introduce such a mechanism because it would be a dangerous back-door.
We have agreed this with CDIO IA and also CCS. See the linked Zendesk ticket above for the paper trail.
Note - this is very dangerous. If you want to run this in future, you should only run it after testing on non-production environments, and with the agreement of
IA.
> Create script to redact data in a brief response

- dmscripts/email_engine/cli.py
- tests/email_engine/test_cli.py
- tests/email_engine/test_email_engine.py
https://trello.com/c/3hLue99t/919-1-finish-creating-a-system-for-bulk-email-scripts-that-is-reliable-repeatable-and-auditable
Bug-fix after #665
Previously although the tests passed in #665 the reference was still being appended erroneously at runtime. Reading `sys.argv` during initialisation resolves this.
> Parse reference using sys.argv

- dmscripts/email_engine/__init__.py
- dmscripts/email_engine/typing.py
- tests/email_engine/test_email_engine.py
- tests/email_engine/test_typing.py
We want to send a unique reference to Notify for every email we send. The reference should be reproducible to allow us to re-create and look up an email's status in our logs at a future date. This is useful when investigating 2nd line requests, or in the face of a potential legal challenge from a supplier.
Scripts not using the email engine already construct this unique reference.
Add a property `EmailNotification.sha256_hash` which computes the SHA256 hash on the string representation of the object.
`EmailNotification` already implements the `__hash__()` method, however this is salted with a random value which changes between Python processes[[1]] and therefore cannot be used to re-create a reference at a future date.
https://trello.com/c/jsjBYAIm/1572-emailengine-does-not-use-unique-refe …
> Pass notification hash to Notify

- scripts/oneoff/get-buyers-for-lot-opted-in-for-research.py
https://trello.com/c/haekzoqW/941-10-recruitment-for-dos-ir35-buyers-of-specialists-research
The admin frontend will give us a list of all buyers who've opted in to being contacted about user research. However, for this particular bit of research, we only want to contact those who've used the Digital Specialists lot.
Just a one-off script for now. If we end up having to run this again, we should consider moving the functionality into admin frontend.
> Get buyers for research who've used a lot

- dmscripts/data_retention_remove_user_data.py
- dmscripts/helpers/auth_helpers.py
- scripts/remove-user-personal-information.py
https://trello.com/c/LUM3xADl/1552-2-script-manually-triggered-deletion-of-a-users-pii
Create a script to automate the [process](https://alphagov.github.io/digitalmarketplace-manual/2nd-line-runbook/support-tasks.html#removing-personal-data) which we've previously done manually.
This should save significant time by removing the need for developers to log in to mailchimp to perform the removal manually.
Do some refactoring to allow us to re-use existing PII deletion functionality.
From my testing, this seems to work on Preview. Once it's been reviewed, I'll test it using [a real deletion request](https://govuk.zendesk.com/agent/tickets/4582433) against production before merging.
> Automate process to remove a user's personal information

- requirements.in
- requirements.txt
Pinning to python-json-logger 0.1.8 was blocking us from upgrading content loader and utils. Upgrade them. Also switch to the version in pypi.org since that's faster to install/pull than git.
No changes that look scary: https://github.com/madzak/python-json-logger
Includes https://github.com/alphagov/digitalmarketplace-scripts/pull/676 and https://github.com/alphagov/digitalmarketplace-scripts/pull/675
> Upgrade python-json-logger to unblock lib upgrades

- .github/workflows/test.yml
Follow-up to #679 
Restore this whilst we work out if script on Jenkins still use it, or if Jenkins can be updated.
> restore testing on 3.6

- scripts/review-dependabot-prs.py
Currently, we need to review, approve and merge some tens of Dependabot PRs each week. The actual reviewing is not very hard - its usually obvious whether to approve a Dependabot PR.
The main problem is that the process involves so many manual clicks. To go from the search page to the PR, approve, and the merge takes at least 4 clicks across 3 pages.
Thus, I'm creating this script to automate the parts of this process that can be automated. It searches for Dependabot PRs, skipping those that are obviously not ready for merging. It then opens the PR in the browser for a human to do the review. The human then just needs to enter 'y' for the PR to be approved and merged.
I think this will cut down quite significantly on the time and effort of dealing with Dependabot PRs.
> Create a script to make Dependabot PRs easier to handle

- scripts/review-dependabot-prs.py
In review-dependabot-prs.py, we were using a new parameter that was not available in Python 3.6 (https://docs.python.org/3.6/library/subprocess.html). Revert to the old way of capturing output (that still works in 3.9).
I can confirm that the script now runs on Python 3.6
> Stop using python 3.9-only features

- dmscripts/export_dos_opportunities.py
- tests/test_export_dos_opportunities.py
https://trello.com/c/sFKzViM7/55-track-the-ir35-determination-of-dos-opportunities
We recently added this new field to briefs, so should add it to the data export as well. CCS have explicitly asked for it. It's already public information, so fine to include here.
Also incidentally fixed a minor type error.
~In draft until late afternoon on the 25th, when we'll have some closed opportunities with employment statuses to test this with. It's a pretty simple change, so I'm not expecting any problems, though.~
> Include employment status in brief export

- scripts/export-approved-service-edits.py
- scripts/oneoff/export-approved-service-edits.py
Previously, we had to do some rather hacky search to get audit events acknowledged in the interval of interest. This was because they were sorted by creation date by default. We made an assumption that events would always be acknowledged within 5 days, which might be a risky assumption over the end of year holiday period.
Take advantage of a new API feature (https://github.com/alphagov/digitalmarketplace-api/pull/1147) to get the audit events already sorted by the date they were acknowledged. This significantly simplifies the logic, slightly improves performance, and removes some potential edge cases.
Just finishing off something I noticed last time I was on support. I've tested this locally, and it doesn't obviously break anything.
Also move the script to a more sensible directory.
> Sort approved service edits in the API

- dmscripts/generate_database_data.py
- scripts/generate-database-data.py
- tests/test_generate_database_data.py
The first stage of my firebreak project.
We've discovered that the API will start against a local database as long as the required tables exist - it doesn't matter if there's no data in any of the tables. This means we can use the API client to insert our randomised data and benefit from all the validation and error handling that the API brings.
Currently this script only adds a single buyer user account, but it sets up a proof of concept for future steps.
https://trello.com/c/RNssJN4U/99-generate-data-for-locally-developing-the-dmp-rather-than-importing-cleaned-production-data
> Add initial script to generate data for the DMp

- scripts/review-dependabot-prs.py
Dependabot PR titles are of the form "Bump X from Y to Z". So by sorting by title, we'll group together updates to the same dependency. This should make it easier to handle all PRs for one common dependency at the same time.
> Sort dependabot PRs by title

- dmscripts/generate_database_data.py
- scripts/generate-database-data.py
- tests/test_generate_database_data.py
This PR makes two changes that mean `scripts/generate-database-data.py` can now run against a database with tables set up but no data.
Firstly, fix a mistake with the email address key when using the API client to create a user.
Secondly, add a new function to add a domain to the list of approved buyer email domains. This has to happen before we try to add any buyer user accounts.
https://trello.com/c/ZAbcTEKR/106-3-create-script-to-generate-test-data-without-dependency-on-any-private-asset
> Fix data generation script

- tests/test_generate_database_data.py
Most of the tests for this script will be similar and need a mocked API client. Add a common base class so we don't need to keep repeating the `setup_method` and `teardown_method` methods each time.
https://trello.com/c/ZAbcTEKR/106-3-create-script-to-generate-test-data-without-dependency-on-any-private-asset
> Add a test base class for generating data

- dmscripts/generate_database_data.py
- scripts/generate-database-data.py
- tests/test_generate_database_data.py
Applying only the database migrations to an empty database creates several old frameworks in various states. This causes problems when the frontend apps try to load content for frameworks we don't have content for (eg. G-Cloud 5).
Set all existing frameworks  to expired before we start adding new data.
https://trello.com/c/ZAbcTEKR/106-3-create-script-to-generate-test-data-without-dependency-on-any-private-asset
> Set all frameworks to expired

- dmscripts/generate_database_data.py
- tests/test_generate_database_data.py
`data.get_buyer_email_domains_iter` returns a list of dictionaries, not just approved domains, so this function raised an error if the domain name was already in the database.
The structure of the returned dictionary: 
```
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.
local rw
In [1]: [i for i in data.get_buyer_email_domains_iter()]
Out[1]: [{'domainName': 'user.marketplace.team', 'id': 1}]
```
> Fix adding a buyer email domain

- dmscripts/generate_database_data.py
- scripts/generate-database-data.py
- tests/test_generate_database_data.py
Based on G-Cloud 12 as that's the most recent G-Cloud framework at time of writing.
https://trello.com/c/ZAbcTEKR/106-3-create-script-to-generate-test-data-without-dependency-on-any-private-asset
> Add a live g-cloud framework to generated data

- scripts/oneoff/add-external-collaborator.py
We have a lot of repos, so manually adding an external collaborator for each is painful. Create this script to invite someone as an external collaborator to all Digital Marketplace repositories. We'll use this to give CCS techops people the ability to create/merge PRs to our repos before we move the repos over to their organisation.
Whilst this will save us a bunch of time, it will still be painful for the person we've invited, since they'll need to accept each invitation manually. Though they could automate this if they wanted to (https://docs.github.com/en/rest/reference/repos#list-repository-invitations-for-the-authenticated-user).
> Create script to add external collaborator

- scripts/create_test_users.py
Tidy up a script we used for the DOS 5 performance testing. Stop hard-coding the user - it's no longer necessary, and is confusing people.
Also run a formatter, and mark a potential secret as safe.
> Tidy up scripts/create_test_users.py

- dmscripts/generate_database_data.py
- scripts/generate-database-data.py
- tests/test_generate_database_data.py
Problem we faced: with GCloud being live we couldn't add suppliers to the framework. This PR first opens GCloud12 and then make it live. This lays the ground for being able to add suppliers to the framework between the framework being open and live.
I have added/edited unit tests. I've also tested this on an empty db and it seems to work.
> Change test data to open GCloud12 before making it live

- scripts/review-dependabot-prs.py
It seems that `gh` doesn't follow the redirect for the repos we've moved from `alphagov` to `Crown-Commercial-Service` when using it like this. Update the org name so this script still works.
> Change Github organisation to CCS

- requirements-dev.txt
- requirements.in
- requirements.txt
- scripts/framework-applications/export-mailchimp-coming-emails.py
- scripts/framework-applications/generate-email-list-for-coming.py
https://trello.com/c/xkosxLyt/128-2-automatically-extract-the-correct-set-of-emails-from-mailchimp
We send an email 1-2 weeks before a new framework opens to let people know about the new framework: https://trello.com/c/qqyRSPut/21-announce-that-new-framework-is-coming-1-2-weeks-before. The process for sending this email is currently very manual (see linked Trello card). For DOS 5, we made a mistake during the manual process. We exported the wrong list, so didn't notify everyone we ought to. Create a script to get the list of email addresses. This should make the process considerably quicker, easier, and safer in future.
I've tested this on Preview - all looks correct. We'll need to update the documentation after this gets merged.
Relies on …
> Generate email list for 'coming' email

- dmscripts/helpers/search_filters.py
- scripts/framework-applications/scan-g-cloud-services-for-bad-words.py
- scripts/maintenance-mode-pr.sh
- scripts/oneoff/add-external-collaborator.py
- scripts/oneoff/add-licence-info-to-readme.sh
- scripts/oneoff/inject-framework-dates.py
- scripts/rotate-api-tokens.sh
- tests/test_notify_suppliers_whether_application_made_for_framework.py
https://trello.com/c/MYdNqOcQ/2331-remove-brett-%F0%9F%91%8B
https://trello.com/c/lvNKNOnS/2329-remove-alex-%F0%9F%91%8B
We're now on 'Crown-Commercial-Service' - not 'alphagov'. Update the scripts accordingly. This should allow us to rotate tokens once again - we're currently getting unexpected responses from the GitHub API because we're using the old organisation name (https://ci.marketplace.team/job/rotate-api-tokens/46/consoleFull).
> Update GitHub org name

- scripts/review-dependabot-prs.py
We no longer use the seal now that we're in the CCS org. So we can instead use the API to get all repos associated with the root DMP GitHub team.
I've tested that this appears to work correctly.
> Get list of DMP repos from API

- scripts/get-suppliers-with-copyable-services.py
https://crowncommercial.zendesk.com/agent/tickets/30475
As part of performance testing for G13/DOS6, we need to have a good number of suppliers with copyable services/declarations to test the service copying journey. Get eligible suppliers and remove their data for the new framework so they're ready for the testing.
> Get suppliers with copyable services

- scripts/get-suppliers-with-copyable-services.py
Commits:
- Make sure only suppliers who have returned the agreement are added
- Add ability to specify a limit for the number of suppliers requires
- Add ability to create file with suppliers
After talking with Toyin, we found a slight issue with the script in that it would include suppliers who had not agreed the previous framework and could therefore not copy services for it. To fix this I added the argument `agreement_returned=True` so we only got valid suppliers.
As Naresh wants a variable number of accounts for each framework, I added the option to specify a limit to the number of supplier accounts. And so that we don't have to copy it all from the console, I changed it to output to a CSV file.
> Update script to get supplier accounts for suppliers who have copyable services

- scripts/api-clients-shell.py
This will allow us to use the `api-clients-shell.py` script in the NFT environment.
> Add NFT to list to access api client shell

- scripts/get-suppliers-with-copyable-services.py
- scripts/get-suppliers-with-unsigned-framework-agreements.py
Using the script in `mark-definite-framework-results.py` I was able to determine some logic to find the suppliers we were after.
I used what I had done in https://github.com/Crown-Commercial-Service/digitalmarketplace-scripts/pull/735 for the spreadsheet generation.
> Create script to get suppliers who have not signed the framework agreement

- scripts/oneoff/get-brief-usage-data.py
https://crowncommercial.zendesk.com/agent/tickets/30866
We've had a request to repeat [scripts/oneoff/get-buyer-usage-data.py](https://github.com/Crown-Commercial-Service/digitalmarketplace-scripts/pull/727), but for DOS briefs. The category team will use this to help project traffic for DOS6. We already have most of this data in the public export of opportunity data, but this should save time for the category team.
> Get stats on brief usage by buyers

- scripts/get-suppliers-on-last-specified-framework.py
- Create script for getting suppliers who have not applied to a new framework
Another request for data from the testing team, this script creates a CSV of suppliers who have not applied to a new framework after the last they have applied for.
For example, if you were to run:
```
./scripts/get-suppliers-on-last-specified-framework.py nft g-cloud-8
```
The list of supplier accounts you get will have applied to g-cloud-8 but not:
- g-cloud-9
- g-cloud-10
- g-cloud-11
- g-cloud-12
> Script for getting suppliers who've only applied to older frameworks.

- scripts/review-bot-prs.py
This has caught out a couple of people now. Provide a more useful error that should make it more obvious what one needs to do.
Example of output:
```
$ scripts/review-bot-prs.py dependabot
You are missing the `gh` CLI tool. Install it from https://github.com/cli/cli#installation
Traceback (most recent call last):
File "/Users/benjamin.gill/code/digitalmarketplace-scripts/scripts/review-bot-prs.py", line 101, in <module>
check_gh_installed()
File "/Users/benjamin.gill/code/digitalmarketplace-scripts/scripts/review-bot-prs.py", line 95, in check_gh_installed
raise e
File "/Users/benjamin.gill/code/digitalmarketplace-scripts/scripts/review-bot-prs.py", line 92, in check_gh_installed
subprocess.run(["which", "ghy"], check=True)
File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framewo …
```
> Provide a good error message if gh is not installed

- scripts/api-clients-shell.py
I was using it to get a user into the correct state for a specific test (https://crowncommercialservice.atlassian.net/browse/OST-114).
Also move the ro/rw prompt components out of the environment formatting dict - I think it makes it slightly clearer.
> Add support for running the API shell for the UAT environment

- scripts/framework-applications/generate-email-list-for-coming.py
https://crowncommercial.zendesk.com/agent/tickets/32738
Following a review of the original list of emails for the DOS6 coming email, we've decided to expand the logic to include more suppliers and people. See commits for details.
I tested by running `scripts/framework-applications/generate-email-list-for-coming.py production 2019-10-01 digital-outcomes-and-specialists-4  digital-outcomes-and-specialists-5 > dos6-coming-email-list-preview-2.csv`. I can confirm that the output file now contains the two domains that David asked to ensure were included (see ticket).
I'd like to try to automate finding the `notify_since_date`. But I don't think that's essential and we're running out of time. So I think this is fine as-is, and I'll try to make it better if I have time later.
> Send DOS6 coming email to more people

- scripts/remove-user-personal-information.py
https://crowncommercial.zendesk.com/agent/tickets/33434
Previously, `remove-user-personal-information.py` required the email address to correspond to a DMP user account. Remove this restriction. This will allow us to delete a user's data from Mailchimp even if they don't have a DMP account.
For such a user, this will now look like:
```
$ ./scripts/remove-user-personal-information.py production foo@example.com
2022-01-21 12:24:47 GMT script INFO User does not have an account on the Digital Marketplace
2022-01-21 12:24:47 GMT script INFO Checking mailing list membership for email with hash abcdef (user n/a)
...
```
> Delete data of users on mailchimp but not DMP

- scripts/framework-applications/snapshot-framework-stats.py
We've not currently got a way to upload stats to Google Drive and recreating it looks to be slow. So instead enhance the snapshot script to it can send the stats in an email. It sends it to a Google Group in the CCS domain so that people who want can access them.
Notify template: https://www.notifications.service.gov.uk/services/a9333c2c-e3a5-4eb3-bb28-86f3920c1900/templates/493ede76-d9c8-40b8-b543-1127ccb60674
Cherry-pick of https://github.com/Brickendon-DMp1-5/digitalmarketplace-scripts/pull/51. We need the change in this repo because it's the one that the `ccsdigitalmarketplace/scripts` docker image is built from.
> Email stats snapshot

- dmscripts/export_service_edits.py
- tests/test_export_service_edits.py
Thanks to some unclear naming, we were previously producing a diff of new to old. We actually wanted old to new.
Add tests that prove that the diff is now correct. Also rename parameters to make usage more obvious.
Discovered during https://crowncommercial.zendesk.com/agent/tickets/35580, but only tangentially related.
> Perform service edit diffs the right way round

- dmscripts/export_service_edits.py
- tests/test_export_service_edits.py
A fix for a bug discovered during https://crowncommercial.zendesk.com/agent/tickets/35580
It is valid for the keys to change - users can add/remove answers to optional questions. Since we're getting the data from the database, I think we can be confident that any such changes are valid.
Add tests to check that it's working.
> Add support for diffs with different keys

- scripts/review-bot-prs.py
The snyk bot user raises all the PRs against public repos. However, it can't access our private repos, so PRs for those are created by developers (e.g. https://github.com/Crown-Commercial-Service/ccs-digitalmarketplace-functional-tests/pull/23). Enhance the search/validation logic for bot PRs to catch this.
There's a risk that this will catch non-bot PRs that happen to mention Snyk (like this one!). However, I think we can trust in the common sense of developers to be able to distinguish dependency upgrade PRs from developer PRs that happen to mention Snyk.
> Search for Snyk PRs from any user

- scripts/review-bot-prs.py
Recently, I've found that the script has not picked up Dependabot PRs in some repos. I suspect this is because either the number of PRs or the number of repos is too large. Work around this by running the search indivually for each repo, to guarantee we get all the PRs. It makes the script a bit slower to run, but more comprehensive.
Also, some repos have no status checks. We still want to be able to review and merge PRs for those repos.
> Get more PRs to review

- scripts/review-bot-prs.py
Some of our repos don't automatically delete branches after merging. There's no reason to keep the merged branches from bot PRs, so delete them.
> Delete branches after merge

- dmscripts/helpers/auth_helpers.py
- scripts/export-approved-service-edits.py
https://trello.com/c/F0h3RRkV/2494-send-ccs-list-of-approved-service-edits-for-month-past
We've currently got a manual process to create the report and email it to a particular category admin once a month. I'm starting to get bored of this, so would like to automate it. Start uploading the report to S3 and sending an email to notify people that the report is available. I plan to set the DMP team as admins of the group, and add the current admin recipient as a member.
You can see the (successful) result of my testing in https://groups.google.com/a/crowncommercial.gov.uk/g/digitalmarketplace-service-edit-reports. The Notify template is: https://www.notifications.service.gov.uk/services/95316ff0-e555-462d-a6e7-95d26fbfd091/templates/fe4b0ac2-c25f-4b02-a72d-0d5b19819d74
Once this is merged, …
> Upload approved service edit report to S3 and send email

- scripts/oneoff/export_brief_responses.py
For whatever reason, if you don't put in the brief ID when trying to get the brief responses, you can get messed up brief response.
I've changed this script to get the brief response for each brief (rather than just get all the brief response).
Although this is much slower, it does produce accurate data at the end.
> Fix export briefs script for digital outcomes
