- requirements.txt
New SearchAPIClient index and alias related methods are required by
the index-services script.
> Update dmutils to 8.5.0

- dmscripts/generate_user_email_list.py
- requirements.txt
- setup.cfg
- tests/test_generate_user_email_list.py
Updates the user-list generation to use the new endpoint for getting suppliers registered for a framework.
Depends on this Utils PR being merged first:
> Update generate user list script with interested suppliers endpoint

- dmscripts/env.py
- scripts/make-g-cloud-7-live.py
This is the script for launching G-Cloud 7. Opening for early review.
> Make g cloud 7 live

- requirements.txt
- scripts/bad_words.py
Add script to check for blacklisted words within g-cloud services
> Add script to check for blacklisted words.

- scripts/index-services.py
This is needed to prepare a search index in advance of G7 go-live + G5 expires.
> Add optional list of slugs of the frameworks to index as a parameter

- scripts/oneoff/fix-agreement-extensions.py
Some signed agreements were uploaded as PDFs when the files were not
PDFs.
> Add script to fix agreement uploads

- requirements.txt
- scripts/get-service-editing-urls.py
Values are hard coded as this script is currently being used for very small specific task of getting
DOS urls only.
> Add script to get DOS urls

- requirements.txt
- scripts/check-g-cloud-live.py
- scripts/oneoff/move-communications.py
- scripts/set-search-alias.py
Move the G7 communications files to the new bucket while adding the `last_modified` date as a timestamp.
> Add script to move G7 communications

- requirements.txt
- scripts/oneoff/move-communications.py
This fixes a bug around formatting the timestamp in S3 save and list.
> Bump dmutils to 15.9.1

- scripts/generate-user-email-list-applications.py
- scripts/generate-user-email-list-declarations.py
- scripts/oneoff/rename-west-england.py
This script will rename West England to South West England in all DOS
draft submissions.
> Add script to rename West England in DOS

- dmscripts/export_dos_suppliers.py
- tests/test_export_dos_suppliers.py
[#111599742](https://www.pivotaltracker.com/story/show/111599742)
> Add additional company info to DOS export

- dmscripts/export_dos_suppliers.py
- scripts/export-dos-labs.py
- tests/test_export_dos_suppliers.py
[#113003693](https://www.pivotaltracker.com/story/show/113003693)
> Export information about DOS labs

- scripts/oneoff/rename-dos-locations.py
Migrates outcomes and recruitment locations to plain old `locations`.
> Rename dos locations

- requirements.txt
- scripts/export-dos-outcomes.py
- scripts/export-dos-participants.py
They were changed in vertion 18.0.0 of utils.
> Fix how DOS locations are handled

- scripts/make-dos-live.py
This has been run on production now - makes sense to save these tweaks to the script for future reference.
Print statements need to be unicode because some supplier names have unicode characters in them.
Catching and reporting errors is better than killing the whole run for a single HTTP error.
> Tweaks to make-dos-live script

- dmscripts/generate_buyer_email_list.py
- scripts/generate-buyer-email-list.py
For this chore: https://www.pivotaltracker.com/story/show/118936027
Script has been run and I've sent the results to Sarah. Adding it here for future use, and for your suggestions for improvements, of course :)
> Add script to export buyer users and their briefs

- dmscripts/generate_buyer_email_list.py
This is useful for getting in touch with only users who are new since the last time you ~~spammed~~ wrote to everyone.
> Include sign-up date in buyer user list export

- scripts/oneoff/generate-g-cloud-8-master-csv.py
Continued from https://github.com/alphagov/digitalmarketplace-api/pull/410
> [#121428145] add generate-g-cloud-8-master-csv.py oneoff script

- dmscripts/generate_agreement_signature_pages.py
- requirements.txt
- scripts/generate-agreement-signature-pages.py
- scripts/generate-g8-signature-pages.py
This is the script that has been used to generate the G-Cloud 8 signature pages.
> G8 signature pages script

- email_templates/requirements_closed.html
Bullet points got lost when I moved the template from the Google doc and I forgot to push this to the branch before I merged the script PR.
> Add bullet points to the requirements closed email template

- dmscripts/bulk_upload_documents.py
- dmscripts/generate_agreement_signature_pages.py
- dmscripts/upload_counterpart_agreements.py
- requirements.txt
- scripts/generate-agreement-signature-pages.py
- scripts/generate-counterpart-signature-pages.py
- scripts/upload-counterpart-agreements.py
- tests/test_bulk_upload_documents.py
- tests/test_upload_counterpart_agreements.py
This has already been run against production for the initial batch of countersigned agreements.
We will soon want to add it as part of a Jenkins job to run periodically, so would be good to get a proper review still!
Tests won't pass now until this is merged:
> Add script to upload counterpart signature pages

- tests/test_generate_user_email_list_applications.py
* Can't rely on order here. Just check the pairs are present and correct
> NO-TICKET-cannot_rely_on_order_here (intermittently failing test)

- schemas/digital-outcomes-and-services-2.declaration.json
doesn't look like anything else is going to check it
> [#134342161]dos2 declaration schema: require "status" field

- dmscripts/generate_framework_master_csv.py
- tests/conftest.py
- tests/fixtures/test_one_supplier_one_lot_result.csv
- tests/fixtures/test_populate_output_suppliers_expected_result.csv
* Remove temporary method for getting supplier `application_status`
* Create stub for `user_export` on `mock_api_client`
* Update tests to reflect new endpoint
> 135223377-part-3-add-application-status-to-master-csv

- dmscripts/generate_questions_csv.py
- scripts/generate-questions-csv.py
Remove hard-coded lots [#136021199]
- default behaviour is now to output all questions, with no
context;
- to choose a specific lot, pass it in using new 'context' CLI
option;
- old behaviour of repeating questions if they appeared in
multiple lots is gone, you can now specify only one lot (or
none, for all questions).
> Question csv download fix

- requirements.txt
to clean up some logging errors
> digitalmarketplace-utils: bump dependency to 23.1.1

- scripts/make-dos-live.py
Was using 'service_id', should be using 'serviceId'
> Fix incorrect key for service ID

- dmscripts/generate_questions_csv.py
- requirements.txt
- scripts/generate-questions-csv.py
- tests/test_generate_questions_csv.py
Changes required as a result of the 'one question per page' thing, and a better understanding of the fields we will expect to be using for G9. Mostly changes around the interpretation of multiquestions and sections.
> Question csv export tweak

- dmscripts/models/queries.py
- scripts/get-model-data.py
- tests/models/test_queries.py
For this pivotal story - https://www.pivotaltracker.com/story/show/140921671
I suggest reading through the 4 commit messages to give you an overview of what this PR contains.
> Create CSV of all DOS services

- scripts/oneoff/generate-fake-g-cloud-services.py
https://trello.com/c/u2CWEhqK/338-creating-dummy-content-to-populate-services-fake-news
> Name index using today's date, so is suitable for use on Preview.

- requirements.txt
pulling in some tiny fixes to improve the user experience of `upload-counterpart-agreements.py`
> digitalmarketplace-utils: upgrade to 25.0.1

- .gitignore
- scripts/get-model-data.py
Trello card: https://trello.com/c/sdwj5wKt/275-add-more-details-to-automatic-data-export-script
> Add more keys to briefs data that gets exported to csv

- scripts/send_dos_opportunities_email.py
As we are now ready to turn the script on.
> Add production list ID's for mailchimp script

- dmscripts/export_framework_applicant_details.py
- requirements.txt
- schemas/g-cloud-9-assessment-schema.json
- scripts/export-framework-applicant-details.py
Adds G9 lots and declaration fields we want to extract.
Also a small bugfix.
Tests are now dependent on this being merged:
> Final script tweaks for g9 closing

- README.md
- scripts/scan-g-cloud-services-for-bad-words.py
Also renames the script to reflect the fact that it doesn't scan drafts, only "real" services.
> Update bad words script with G9 text fields

- dmscripts/helpers/env_helpers.py
To be merged after the PaaS switch
> Remove old preview and staging domains from env helpers

- README.md
The agreements repo has moved from github enterprise to github.com
> Update README with new github url

- scripts/scan-g-cloud-services-for-bad-words.py
We have a shiny new aplhagov repo so update comment to refer to it.
> Update URL for bad words repo

- scripts/oneoff/migrate-supplier-data-from-declarations.py
Story https://trello.com/c/v0ouuEMF/61-migrate-the-data-from-the-g9-dos2-declaration-to-account-level-2
Most of the information about this is in that story, including example "dry run" output run on production yesterday with outputs of what changes it *would* make.
> add migrate-supplier-data-from-declarations script

- scripts/update-index-alias.py
The update index alias script has failed a few times recently but doesn't spit out much useful information to the logs. Adding this to hopefully help on the chance it goes wrong again.
> Add details to update index script

- requirements-app.txt
- requirements.txt
- scripts/upload_dos_opportunities_email_list.py
> Requirements utils-27.1.2 > utils-28.7.0

- scripts/api-clients-shell.py
Data api client isn't set up correctly for stages due to hanging comma.
> Hanging comma turns variable into a tuple

- dmscripts/models/process_rules.py
- dmscripts/models/queries.py
- scripts/get-model-data.py
- tests/models/test_queries.py
https://trello.com/c/5rEnbBR5/105-create-complete-opportunity-data-script-to-publish-on-the-digital-marketplace-automated
Create a new csv.
Tidy up some of our csv creation.
> 105-create-complete-opportunity-data-script-to-publish-on-the-digital-marketplace-automated

- scripts/get-model-data.py
Drop duplicates fix
Only return info for dos2
> Bugfixes for scripts/get-model-data.py::opportunities-data

- scripts/index-services.py
Exception format from Elasticsearch client has changed; now returns a dict rather than a string.
Also automatically decode credentials for tokens by stage, if not supplied manually.
https://trello.com/c/wxoYb6sT/9-investigate-how-to-upgrade-elastic-search-so-it-is-ready-to-move-to-paas
> Stringify (dict) error message from Elasticsearch

- .flake8
- dmscripts/models/queries.py
- scripts/get-model-data.py
- tests/models/test_queries.py
Need this because we need 2 fields derived from a brief_id
https://docs.google.com/a/digital.cabinet-office.gov.uk/spreadsheets/d/19ULqnNcrogqd47NrLrsoK9FMjVIUbtSXxhhqPFeqK-g/edit?usp=sharing
https://trello.com/c/5rEnbBR5/105-create-complete-opportunity-data-script-to-publish-on-the-digital-marketplace-automated
> New duplicate fields option

- scripts/get-model-data.py
* Show all opportunities
* Add default to `requirementsLength`
> Tweaks for opportunities data csv

- dmscripts/helpers/auth_helpers.py
- scripts/index-services.py
1. Allow auth token helpers to match dev aliases
2. Update docstring to better reflect script use
> Update indexing script to be more user friendly

- .flake8
- dmscripts/notify_suppliers_of_brief_withdrawal.py
- tests/test_notify_suppliers_of_brief_withdrawal.py
Does not need .get for iterator method
> Bugfix to digitalmarketplace-scripts/dmscripts/notify_suppliers_of_brief_withdrawal.py

- requirements-app.txt
- requirements.txt
- scripts/index-services.py
Update index-services script to have a default mapping (for services) to remain compatible after updates to the search-api/apiclient
> Update indexing script

- README.md
- scripts/oneoff/generate-fake-g-cloud-services.py
Updates documentation:
Changes index-services.py filename to index-to-search-service.py
Ticket:
https://trello.com/c/5oIKvS1s/100-search-service-for-briefs-plus-indexing-script
> Updates documentation: Changes index-services.py filename to index-to-search-service.py

- scripts/update-index-alias.py
The existing help string confused the flip out of me earlier trying to debug something it had done.
> update-index-alias.py: improve help string describing behaviour

- dmscripts/send_stats_to_performance_platform.py
- scripts/send-stats-to-performance-platform.py
- tests/test_send_stats_to_performance_platform.py
Update the script for sending framework application to the performance platform to use Python3; re-jig import statements
https://trello.com/c/mtiS5IAx/3-move-scripts-running-python-2-on-jenkins-to-python3-docker
> Make script Python3 compatible

- Dockerfile
- requirements-app.txt
- requirements.txt
- scripts/rotate-api-tokens.sh
Adds a script that allows easier rotation of tokens for our data and
search API. The script will add three new tokens, or remove all except
the top three, commit the new tokens, push them to GitHub and open a
Pull Request for review. This will integrate with a Jenkins pipeline job
that will add new tokens, re-deploy all apps, then remove the old tokens
and re-deploy all apps to hopefully make it far faster and less
error-prone to cycle tokens.
https://trello.com/c/4crGe6F0/169
> Automated API token updates

- scripts/oneoff/migrate-supplier-organisation-size-from-declarations.py
Have run this against prod with the `--dry-run` flag and it seems to hoover up
the straggling suppliers. 
The script was ordering supplier frameworks by there
`agreementReturnedAt` date. In some instances however the agreement
hadn't been returned and so this value was `None`. These instances seemed
to be either when a supplier was not on framework and so potentially had
a half complete declaration, or some G7 supplier frameworks didn't have
this date set.
When ordering by `agreementReturnedAt` any framework with `None` for
this date would always appear at the beginning of the list and so be
selected. The knock on effect being that there was a high chance that
it didn't have a correct value for `organisationSize` in the declaration
and so the suppliers `organisation_size` would not be …
> Fix bug with org size migration script

- scripts/rotate-api-tokens.sh
We have added a new token to the API for callbacks from Notify, so we
need to be able to rotate it on demand. This update to the
`rotate-api-tokens.sh` script will allow us to create a new Jenkins job
that can rotate the Notify callback token.
> Rotate callback tokens

- scripts/rotate-api-tokens.sh
The method for adding a new Notify callback token had a hardcoded
reference to the preview variables file. This needs to go!
> Hardcoded preview environment

- dmscripts/mark_definite_framework_results.py
Display on stdout the number of interested suppliers and where you are
in the list of all suppliers being worked on so that you can more easily
estimate how long the script will take to finish.
> Add more info to logs

- scripts/generate-framework-agreement-counterpart-signature-pages.py
- scripts/generate-framework-agreement-signature-pages.py
We broke the interface into `get_csv_rows` to add a required parameter
of `framework_lot_slugs`. Some other scripts depended on this interface
and so need updating.
> Update generation scripts with lot slugs

- requirements-app.txt
- requirements.txt
Updated to the latest version
There was a bug in v0.1.5 where the version number is incorrect, which
was causing issues with the Dockerfile
> Update python-json-logger in requirements

- scripts/publish-g-cloud-draft-services.py
Allow specifying a set of drafts to try publishing and copying documents
from submissions->documents bucket again, in case of a failed attempt on
the original run.
> Re-publish documents for drafts

- scripts/publish-g-cloud-draft-services.py
> Starts with, not equals

- scripts/scan-g-cloud-services-for-bad-words.py
The list is now an amalgamation of all keys checked for G7 through G10.
I did want to remove this list completely and just scan any value in the
service data that was of string type. Unfortunately we have list
questions, and checkbox questions, which both appears as lists of
strings in the data.
The strings from checkbox questions are defined by us, and they may
include words defined in our list of bad words (words given to us by
CCS, not naughty words). This means we could get some false positives.
> Add G10 service keys to bad words script

- scripts/publish-dos-draft-services.py
> Make `publish-dos-draft-services.py` executable

- scripts/rotate-api-tokens.sh
Trello: https://trello.com/c/1rG2cFj3/191-include-antivirus-api-in-token-rotation-job
The Antivirus API tokens should be included in the token recycle script.
Jenkins doesn't use `DM_ANTIVIRUS_API_TOKEN` so we don't need to add it to the `get_jenkins_env_token_name` function.
Updates to the Jenkins job (to re-release the Antivirus API as part of the token recycle pipeline) here: https://github.com/alphagov/digitalmarketplace-jenkins/pull/147
> Include Antivirus API token in token rotation script

- .flake8
- pytest.ini
- requirements-dev.txt
- setup.cfg
This PR updates the packages we use for testing scripts
> Update dev requirements

- dmscripts/virus_scan_s3_bucket.py
- scripts/virus-scan-s3-bucket.py
- tests/test_virus_scan_s3_bucket.py
This PR AKA "how to multithread a command-line script". Not that I'm being opinionated or anything.
https://trello.com/c/aWnL8fAa/192-antivirus-create-catch-up-bulk-scan-script
Importantly retaining the flexibility to use a regular `map` implementation to disable any threading complexity.
> virus_scan_s3_bucket: multithread main loop

- requirements-app.txt
- requirements.txt
Reverts alphagov/digitalmarketplace-scripts#299
> Revert "Update app requirements file"

- dmscripts/data_retention_remove_supplier_declarations.py
- dmscripts/helpers/supplier_data_helpers.py
- scripts/data-retention-remove-failed-suppliers-declarations.py
- scripts/data-retention-remove-supplier-declarations.py
- tests/helpers/test_supplier_data_helpers.py
This is to fixup something @benvand spotted. I've changed over the record for the audit event so that it's got more detail, in case we need to go back and check what happened when.
> Fixup audit event

- dmscripts/export_outcomes_to_csv.py
- requirements-app.txt
- requirements.txt
- scripts/export-outcomes-to-csv.py
- tests/test_export_outcomes_to_csv.py
https://trello.com/c/t2N1EqPk
I can't think of much interesting to say about this.
> add export-outcomes-to-csv script

- dmscripts/data_retention_remove_user_data.py
- scripts/data-retention-remove-user-data.py
Again with https://trello.com/c/QROOUpoX
Remind me again why we're using docopt?
> data-retention-remove-user-data: get mailchimp credentials from args the way docopt wants

- .gitignore
- Makefile
- dmscripts/export_framework_applicant_details.py
- dmscripts/generate_framework_agreement_signature_pages.py
- dmscripts/helpers/framework_helpers.py
- dmscripts/helpers/logging_helpers.py
- dmscripts/models/modeltrawler.py
- functional-tests/README.md
- functional-tests/generate-framework-agreement-signature-pages/README.md
- functional-tests/generate-framework-agreement-signature-pages/setup.sh
- functional-tests/generate-framework-agreement-signature-pages/signature-pages.t
- functional-tests/generate-framework-agreement-signature-pages/suppliers.t
- functional-tests/generate-framework-agreement-signature-pages/usage.t
- functional-tests/setup.sh
- requirements-dev.txt
- scripts/generate-framework-agreement-signature-pages.py
- tests/helpers/test_framework_helpers.py
- tests/test_generate_framework_agreement_signature_pages.py
https://trello.com/c/jEZzVo2u/326-tidy-signature-page-generation-script
Refactoring the signature page generation script to be more verbose and more user-friendly.
Now with added functional tests! Functional tests require https://github.com/alphagov/digitalmarketplace-test-utils/pull/20, Travis won't pass until this is merged.
> Tidy signature page generation script

- scripts/generate-framework-master-csv.py
Trello: https://trello.com/c/o8pZ2vJH/412-generate-framework-master-csv-script-doesnt-automatically-output-into-a-file
- Adds an extra argument for an output dir
- Checks that the folder exists
- Builds a sensible filename from the slug, stage and date
- Passes the file path through to the CSV builder.
> Master framework export script can output to a file

- scripts/oneoff/update-supplier-data.py
This is a one-off script that needs a CSV input. The column titles should be 'DMP record ID', 'Field Name for update', and 'New Value'. It'll go through and update the value given.
As it stands this has too many prints, but the data needs testing before we commit to running it.
[Ticket for context](https://trello.com/c/RMLrneG5/423-data-controller-batch-update)
> Add script to update supplier attributes

- scripts/oneoff/export-service-categories.py
Trello: https://trello.com/c/f0BSSc6s/32-send-ccs-an-export-of-all-g10-services-including-service-descriptions
Ash (on behalf of CCS) has requested the service description to be included in the services export, so that qualitative data analysis on the services can be carried out.
> Add service description to export script

- default.nix
- dmscripts/helpers/framework_helpers.py
- dmscripts/helpers/logging_helpers.py
- dmscripts/publish_draft_services.py
- requirements-dev.txt
- scripts/framework-applications/publish-draft-services.py
- tests/helpers/test_framework_helpers.py
- tests/test_publish_draft_services.py
~A draft because it's still missing tests, but script seems to work from my ad-hoc testing so take a look.~
https://trello.com/c/V2miZJ5G
Should be ready to review now, has a _reasonable_ level of testing - a few corner cases missed out though.
> add new generalized & refactored publish-draft-services.py script 

- schemas/g-cloud-11-assessment-schema.json
Trello: https://trello.com/c/9PHHg4X3/509-generate-g11-declaration-assessment-schema-ko-w-kat
Adds the pass/fail schema generated by https://github.com/alphagov/digitalmarketplace-frameworks/pull/569.
> G11 declaration assessment schema

- dmscripts/generate_framework_master_csv.py
- scripts/framework-applications/generate-framework-master-csv.py
- tests/fixtures/test_many_suppliers_many_lots_result.csv
- tests/test_generate_framework_master_csv.py
Fixes up minor bugs discovered during the G11 export.
> Framework master export: handle suppliers with no declaration

- .pyup.yml
https://trello.com/c/mBmxDwfC/823-make-pyup-prs-appear-in-the-morning
They'll appear ready for us on Monday morning.
> Move PyUp alerts to Sunday

- dmscripts/helpers/supplier_data_helpers.py
- functional-tests/functional-tests-tests/environment.t
- functional-tests/notify-suppliers-whether-application-made-for-framework/setup.sh
- functional-tests/notify-suppliers-whether-application-made-for-framework/suppliers.t
- functional-tests/notify-suppliers-whether-application-made-for-framework/usage.t
- functional-tests/setup.sh
- requirements.txt
- scripts/notify-suppliers-whether-application-made-for-framework.py
- tests/conftest.py
- tests/helpers/test_supplier_data_helpers.py
- Reorganise docstring
- Log supplier IDs
- Allow filtering by supplier IDs
This is kind of an MVP first pass, there's a lot more work that could be
done, so sound off if the improvements you want to see are missing.
Ticket: https://trello.com/c/dWKKyhcD/530-improve-notify-suppliers-whether-application-made-or-not-email-job
> Refactor notify suppliers script

- dmscripts/generate_supplier_user_csv.py
- tests/test_generate_supplier_user_csv.py
Send a warning message to the log instead of crashing.
> Fix script to warn when framework is not open

- default.nix
- requirements-app.txt
- requirements.txt
To allow me to test https://trello.com/c/V7cUDIRW
> Bump digitalmarketplace-apiclient dependency to 20.2.0 

- functional-tests/generate-framework-agreement-signature-pages/signature-pages.t
- functional-tests/generate-framework-agreement-signature-pages/suppliers.t
- functional-tests/generate-framework-agreement-signature-pages/usage.t
- scripts/framework-applications/generate-framework-agreement-signature-pages.py
https://trello.com/c/O2bJ3EDP/908-manual-entry-generate-framework-agreement-signature-pagespy-fwapplications
> Move generate-framework-agreement-signature-pages to framework-applications

- dmscripts/index_to_search_service.py
> Add G11 to search mapping

- scripts/publish-g-cloud-draft-services.py
* Add new flag to republish all documents 
* Fix bug when passing in `draft-ids`
https://trello.com/c/xzJGlp3w/582-updates-to-scripts-publish-g-cloud-draft-servicespy
> 582-updates-to-scripts-publish-g-cloud-draft-servicespy

- scripts/oneoff/swap-supplier-duns.py
https://trello.com/c/SYqyW0Zm/954-duns-swap
The DUNS swap script originally required the values to be provided as arguments, for a 'belt and braces' approach to making sure we were setting the correct values. However, in practice:
- errors are more likely to creep in when copying and pasting the values
- CCS don't send the DUNS numbers in the support request emails, just the supplier IDs (which is fair enough, given that we should be able to find the DUNS numbers ourselves from each supplier!)
- if we mistakenly run the script and swap two DUNSes that shouldn't have been swapped, it's easy to fix: simply run the same script call again to swap back.
So I just made the DUNS value arguments optional.
Also: I've been merrily using this branch to do the swaps for the last 2 weeks anyway …
> Allow supplier DUNS swap without providing values

- dmscripts/helpers/supplier_data_helpers.py
- dmscripts/notify_suppliers_with_incomplete_applications.py
- scripts/notify-suppliers-with-incomplete-applications.py
- tests/test_notify_suppliers_with_incomplete_applications.py
trello: https://trello.com/c/0fG8ahIA/546-reminder-email-for-suppliers-with-incomplete-applications
Can I sit with someone opinionated about the structure of script, before I start patching and parametrising tests? and can give me an intro to notify templates?
> One week reminder

- dmscripts/publish_draft_services.py
- scripts/framework-applications/publish-draft-services.py
- tests/test_publish_draft_services.py
https://trello.com/c/fk9G3bkF/1102-remove-reliance-on-function-passing-in-publish-draft-services
> 1102-remove-reliance-on-function-passing-in-publish-draft-services

- docker_for_mac_entrypoint.sh
- requirements-app.txt
- requirements.txt
Ticket: https://trello.com/c/cwjzIU8U/1212-stop-search-api-from-using-port-5001
> Change the default port for the search api

- scripts/notify-suppliers-of-new-fw-cq-answers.py
Silly mistakes/things not changed from the initial copy-pasta.
> notify-suppliers-of-new-fw-cq-answers.py: fixes to docopt string

- scripts/oneoff/update-supplier-data.py
https://trello.com/c/tIkNePEe/
We run this script perhaps once or twice a year when CCS send us over a list of supplier data updates. It isn't particularly well documented (or robust, or tested...) but refactoring it is low priority. I've added a usage example as a bare minimum, to aid future devs who need to run this script.
> Add example to supplier update script

- scripts/framework-applications/snapshot-framework-stats.py
- scripts/snapshot-framework-stats.py
https://trello.com/c/i4mL2aBs/408-export-application-stats
* Make application stats script output to file
* General tidying
> 408-export-application-stats

- README.md
As recommended by the GDS Way. 
(I didn't use the script for this one.)
> Update README with Licence info

- scripts/maintenance-mode-pr.sh
https://trello.com/c/j1kYVu3a/1303-implement-multi-maintenance-mode
Maintenance mode is no longer 'on' or 'off' so the script has been tweaked to accept the string directly. I renamed `COMMAND` to `MODE` to match what we're setting as the environment variable in the AWS repo.
Validation is handled in the same way as for the STAGE parameter.
https://github.com/alphagov/digitalmarketplace-router/pull/81 should be merged and deployed before merging this script.
> Add recovery option to maintenance mode

- requirements.in
- requirements.txt
https://trello.com/c/kCUjDnH4/48-3-3-jenkins-job-for-publish-services
A bit of housekeeping before I tackle the publish-services script.
- Remove old pyup comments (no longer used)
- Bump itsdangerous, to bring in line with the FE apps
- Bump API client to bring in new method
- Bump other dependencies (superseding the dependabot PRs)
> Pull in new API client method for draft services

- dmscripts/export_dos_opportunities.py
- tests/test_export_dos_opportunities.py
https://trello.com/c/0LD5lLbf/95-1-amend-opportunity-data-report
> add clarification question count to csv

- dmscripts/get_log_events.py
- scripts/oneoff/get-log-event-in-epoch-range.py
- scripts/oneoff/get-log-events.py
trello: https://trello.com/c/e04K4fMI/1833-one-off-script-to-retrieve-logs-from-cloudwatch
> Get log events in epoch intervals

- scripts/framework-applications/notify-successful-suppliers-for-framework.py
https://trello.com/c/WkNHIRt7/300-05-tell-successful-suppliers-the-result-intention-to-award-11-sept
Our new template needs some extra dates.
> Add dates to ITA script

- scripts/generate-framework-agreement-counterpart-signature-pages.py
We want to be able to run this script without making database changes; this PR adds a dry-run flag that will prevent agreements from being countersigned (but will allow the script to continue running).
> Add dry-run flag to generate framework agreement counterpart signature script

- scripts/generate-framework-agreement-counterpart-signature-pages.py
It would be nice to know what it's doing even without the verbose flag.
> Tweak counterpart PDF script to be more communicative

- dmscripts/generate_framework_agreement_signature_pages.py
We only want to see warnings or errors from wkhtmltopdf, we don't need the progress bars.
> Change agreement PDF script to be less verbose

- scripts/generate-framework-agreement-counterpart-signature-pages.py
Don't stop running if a supplier framework agreement is in a bad state.
> Handle case where supplier framework agreement is in bad state

- scripts/framework-applications/suspend-suppliers-without-agreements.py
Due to a policy change we now want to allow suspensions during the standstill period.﻿
> allow suspensions during standstill

- scripts/api-clients-shell.py
Make it easy to see which stage your API client is targeting by printing the stage before the usual prompt. `production` comes in red!
[![asciicast](https://asciinema.org/a/VnYSqtygwi70ElcUUqX1R2aAZ.svg)](https://asciinema.org/a/VnYSqtygwi70ElcUUqX1R2aAZ)
> Add custom IPython prompt to API clients shell

- dmscripts/index_to_search_service.py
This is not great, and is going to trip us up next year with G13. Let's do the quick fix now and then do something better later.
> Add g-cloud-12 mapping to index script

- requirements.in
- requirements.txt
https://trello.com/c/kbhJdTm3/567-remove-flaskscript-from-dmutils
> Remove Flask-Script

- scripts/create_test_users.py
Trello: https://trello.com/c/kGmsXWZ1/520-3-find-out-whether-dmp-can-cope-with-dos5-closing
We will use these freshly created suppliers and associated users for [our load testing](https://github.com/alphagov/digitalmarketplace-performance-testing/pull/8)
> Create script to create test suppliers/users

- scripts/oneoff/export-approved-service-edits.py
Ticket: https://trello.com/c/Yg0KjHkw/2050-ccsrequests-service-edits-report
See comit messages for details.
> Fix column order in export approved service edits CSV

- schemas/digital-outcomes-and-specialists-5.declaration.json
Picks up the changes from https://github.com/alphagov/digitalmarketplace-frameworks/pull/654
https://trello.com/c/8tkVDOur/554-05-run-declaration-assessment-script
> Update DOS5 declaration validation schema

- scripts/upload-modern-slavery-statement.py
Trello: https://trello.com/c/vTkIJ4WK/2103-ccsrequests-uploading-a-new-modern-slavery-statement
This script implements the process: https://alphagov.github.io/digitalmarketplace-manual/2nd-line-runbook/support-tasks.html?#adding-or-updating-a-modern-slavery-statement
This should make it faster and less error-prone in future.
Once this is merged, I intend to use it for a real user request to prove that it works. I'll then update the manual.
> Script updating a modern slavery statement

- scripts/upload-modern-slavery-statement.py
I made a few mistakes in https://github.com/alphagov/digitalmarketplace-scripts/pull/583 that I discovered when I first try running the script for real. Fix them.
Once this PR is applied, the script works correctly. I used this on a real supplier who wanted their statement updated, and it worked - see https://www.digitalmarketplace.service.gov.uk/g-cloud/services/184304153782344
> Fix modern slavery statement upload

- scripts/get_active_users_csv.py
https://trello.com/c/foEGJ9le/572-1-prepare-send-comms-to-users-about-the-planned-maintenance-to-release-the-security-fix
Add script for generating list of active users suitable for the task in the linked Trello card.
> Add script for getting active users

- scripts/open-dependabot-prs.sh
I was getting a bit bored of clicking through all the repos to check for Dependabot PRs. So I wrote this script to do it for me.
> Create script to open all Dependabot PRs

- dmscripts/generate_framework_agreement_signature_pages.py
- scripts/generate-framework-agreement-counterpart-signature-pages.py
https://trello.com/c/75hbcRW8/607-3-implement-dos-5-e-signature
Sister PR to https://github.com/alphagov/digitalmarketplace-agreements/pull/12
This is similar to https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/1294 in that we branch on the framework slug to account for framework varience.
> Generate DOS5 agreement

- scripts/framework-applications/notify-successful-suppliers-for-framework.py
https://trello.com/b/qQEocgFk/q3-doing-dmp-lights-on-and-g12-dos5-support
Get framework details from API rather than hardcoding (refactor to address TODO)
> get framework dates from API

- scripts/framework-applications/notify-successful-suppliers-for-framework.py
https://trello.com/c/k2lfAXGt/651-2-prepare-e-signature-related-emails
Add contract title to notify template personalisation so we can include it in the ITA email.
> add contract title to notify template personalisation

- dmscripts/upload_counterpart_agreements.py
- scripts/upload-counterpart-agreements.py
- tests/test_upload_counterpart_agreements.py
https://trello.com/c/k2lfAXGt/651-2-prepare-e-signature-related-emails
Pass contract title to counterpart notification email.
(Note this will require corresponding changes in the Jenkins job which I will pick up in a subsequent PR once approved.)
> add contract title to counterpart notification email

- dmscripts/upload_counterpart_agreements.py
- tests/test_upload_counterpart_agreements.py
https://trello.com/c/k2lfAXGt/651-2-prepare-e-signature-related-emails
> add framework live at date to counterpart notification email

- dmscripts/helpers/framework_helpers.py
https://trello.com/c/qmUdpw9u/656-1-e-signature-cleanup-use-api-boolean-to-check-frameworks
Refactor to use API value rather than hardcoded heuristic
> use API boolean for e-signature rather than hardcoded heuristic

- scripts/oneoff/export-services-by-lot.py
https://trello.com/c/UmnZzV0q/2153-ccsrequests-g-cloud-11-service-data-request
One off script to service the linked ticket.
> add script to export services by lot

- scripts/get_trello_members.py
Trello: https://trello.com/c/bHA7PWRG/2156-audit-all-people-with-access-to-dmp-trello-boards
Create a script that uses the Trello API to get information on the members of all our boards.
We need this because we currently have people who have access to our boards who should not have access.
> Audit members of our Trello boards

- dmscripts/send_dos_opportunities_email.py
- scripts/upload-dos-opportunities-email-list.py
https://trello.com/c/2NoGsRum/663-05-add-successful-suppliers-to-dos-mailchimp-mailing-lists
> Update mailchimp list IDs for DOS5

- scripts/get_trello_members.py
> Add new Trello team to list

- .gitignore
https://trello.com/c/0B9MjEdE/738-05-prevent-people-from-accidentally-committing-pdfs-and-csvs
We want to make it more difficult to accidentally commit PII as this repo contains many scripts which output to disk.
> add csvs and pdfs to .gitignore

- scripts/oneoff/export_brief_responses.py
Add one off script to support data request in: https://govuk.zendesk.com/agent/tickets/4468497
> Export brief responses

- scripts/oneoff/export_brief_responses.py
script was broken as `sys.path.insert(0, '.')` needs to happen before importing from `dmscripts`
> do path insert further up

- scripts/oneoff/get-g12-recovery-draft-status-csv.py
> Add header to G12 recovery draft report

- dmscripts/helpers/search_filters.py
- scripts/oneoff/export-framework-search-filters.py
- scripts/oneoff/export-service-top-level-categories.py
Add script to support data request https://govuk.zendesk.com/agent/tickets/4469876
This borrows heavily from https://github.com/alphagov/digitalmarketplace-scripts/pull/626 for the logic to derive available filters and sub-filters.
> add script to export services top level filter categories

- scripts/oneoff/get-jenkins-functional-test-build-data.py
Adds a new column `framework_state` to the report. Different tests are run in different framework states, so this will allow us to make like-to-like comparisons.
This is only the approximate framework state as reported by the framework closing, live and expiry dates from the API. We can't get the actual state of the DMp on preview or staging at a point in time because we overwrite the audit events table whenever we apply a data dump from production.
The approximation is probably fine for staging since the state in staging is the same as production the vast majority of the time, and the state in production is managed to the timetable dictated by the dates from CCS.
For preview, we often have the environment one step ahead of staging and production, which means this data may be less …
> Add framework state to Jenkins functional test report

- scripts/oneoff/notify_g12_recovery_successful_suppliers.py
https://trello.com/c/FBgpLztJ/845-1-make-successful-services-live
Script to notify successful suppliers as part of G12 recovery.
> add one off script to notify g12 recovery successful suppliers

- scripts/oneoff/export_dos_supplier_subcontracting_responses.py
Add script to support one off data request from: https://govuk.zendesk.com/agent/tickets/4523135
> add subcontracting data one off script

- scripts/oneoff/redact_brief_response.sql
We forgot to add this correction to the original PR and decided to open a small PR with it afterwards.
I... forgot about it and I just noticed it's been sitting on my laptop, so here it is.
You can confirm this is the correct usage by checking the commands we ran in https://govuk.zendesk.com/agent/tickets/4540337
> Correct psql argument in the usage description

- requirements-dev.txt
- requirements.txt
To fix a security issue: https://github.com/alphagov/digitalmarketplace-scripts/security/dependabot/requirements-dev.txt/urllib3/open
Need to do the update manually because Dependabot was struggling.
> Update requests and urllib

- scripts/review-dependabot-prs.py
When reviewing Dependabot PRs, it's handy to know more about the PRs where the check status is not successful. If it's in progress, I don't need to do anything. But I want to know if the check completed but failed, because that means I need to intervene.
Show the details of checks that weren't successful. The format isn't very pretty, but should be good enough for a developer to work out what's going on.
An example of this in action:
```
https://github.com/alphagov/digitalmarketplace-govuk-frontend/pull/367
Wrong check status: [{'__typename': 'CheckRun', 'name': 'test (14.x)', 'status': 'QUEUED', 'conclusion': '', 'startedAt': '2021-07-27T15:34:06Z', 'completedAt': '0001-01-01T00:00:00Z', 'detailsUrl': 'https://github.com/alphagov/digitalmarketplace-govuk-frontend/runs/3173372287'}] …
```
> Show unsuccessful checks

- scripts/review-bot-prs.py
- Identical to the script for dependabot but changed to allow for multiple bot PRs to be reviewed
As we get PRs for snyk as well as dependabot, I thought it might be worth refactoring the script so that it could review PRs for multiple bots.
The only differences between dependabot PRs and snyk PRs are that they have different authors and slightly different labelling. The config for these bots is kept in the `BOTS_CONFIG` and this is used to differentiate them.
Other than that, the script remains unchanged other than exiting if one of the options given is not in the `BOTS_CONFIG`.
> Create script to review bot PRs

- scripts/oneoff/export-declaration-responses.py
https://crowncommercial.zendesk.com/agent/tickets/30228
A supplier has asked for a copy of their declaration responses. Provide this. Also pull the questions from content loader where possible so it's more obvious what the responses are to.
> Create script to export supplier declaration

- scripts/nft-database-backup-config.sh
- Create script which will create PRs for the database restoration
This is meant to be used within Jenkins, I'm not 100% sure it will work for the NFT environment but I will try it out.
However, I have checked that all the steps work locally with my own Git config.
I've also made it so that the output is silent expect for the PR it creates.
> Create script which will create PRs for the database restoration

- scripts/get-suppliers-with-suspended-services.py
This is script which, like many of the others we have done for the testers, gets a list of suppliers that meet certain requirements.
I this case, the requirement is that the supplier has a suspended service.
> Create script to find suppliers with suspended services

- scripts/nft-database-backup-config.sh
Now we have a new repo for the NFT code (https://github.com/Brickendon-DMp1-5/digitalmarketplace-aws), we need this script to commit to this instead.
> Change script to commit to new AWS repo

- scripts/oneoff/fill-declaration-answers.py
https://crowncommercialservice.atlassian.net/browse/OST-114
My previous attempt (https://github.com/Crown-Commercial-Service/digitalmarketplace-scripts/pull/745) didn't quite work. All the DOS 5 suppliers were also on G12, and G12 overrode DOS5 by dint of being later.
So to test copying from DOS5, we need suppliers who weren't on G12.
> Generate suppliers to test copying from DOS5

- dmscripts/get_user.py
- dmscripts/helpers/supplier_data_helpers.py
- dmscripts/notify_buyers_when_requirements_close.py
- dmscripts/virus_scan_s3_bucket.py
- requirements-dev.in
- requirements-dev.txt
- scripts/export-dos-labs.py
- scripts/framework-applications/generate-framework-agreement-signature-pages.py
- scripts/framework-applications/update-framework-results.py
- scripts/get-suppliers-with-copyable-services.py
- scripts/get-suppliers-with-unsigned-framework-agreements.py
- scripts/oneoff/upload_draft_service_pdfs.py
- scripts/update-index-alias.py
- tests/test_send_stats_to_performance_platform.py
Add support for new Python features, including the new walrus operator introduced in Python 3.8.
Fix the various new things flake8 warns us about - see individual commits for details.
Cherry-picked from https://github.com/Brickendon-DMp1-5/digitalmarketplace-scripts/pull/52
> Upgrade to flake8 4.0.1

- dmscripts/export_dos_opportunities.py
- scripts/export-dos-opportunities.py
- tests/test_export_dos_opportunities.py
https://crowncommercial.zendesk.com/agent/tickets/39412
The category team have asked us to add this field to the export.
> Include budget range in DOS opportunity export

- requirements.in
- requirements.txt
Reverts Crown-Commercial-Service/digitalmarketplace-scripts#847
> Revert "Bump pypdf2 from 2.12.1 to 3.0.1"
